replicaCount: 4
volumeMountPath: 'shared-volume'
nginxServiceName: nginx-web-app
branch: 'main'

config:
  MONGO_URI: mongodb://mongo-api.video-downloader.svc.cluster.local

image:
  registry: christopherguzman
  repository: video-downloader-api
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000

ingress:
  enabled: true
  host: api.vd.iguzman.com.mx

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

deployment:
  nodeSelector:
    nodeProjects: real-clients
