# Generated by Django 5.2.11 on 2026-07-17 00:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0012_product_video_link_service_video_link'),
        ('core', '0023_system_stripe_enabled_system_stripe_publishable_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('MXN', 'Mexican Peso'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('ARS', 'Argentine Peso'), ('COP', 'Colombian Peso'), ('CLP', 'Chilean Peso'), ('BRL', 'Brazilian Real')], default='USD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('shipping_name', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_line1', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_line2', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_city', models.CharField(blank=True, default='', max_length=128)),
                ('shipping_state', models.CharField(blank=True, default='', max_length=128)),
                ('shipping_postal_code', models.CharField(blank=True, default='', max_length=32)),
                ('shipping_country', models.CharField(blank=True, default='', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('variant_label', models.CharField(blank=True, default='', max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=128)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('MXN', 'Mexican Peso'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('ARS', 'Argentine Peso'), ('COP', 'Colombian Peso'), ('CLP', 'Chilean Peso'), ('BRL', 'Brazilian Real')], default='USD', max_length=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.product')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.productvariant')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.service')),
                ('service_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.servicevariant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['system', 'status'], name='orders_orde_system__19d3b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_line_quantity_positive'),
        ),
    ]
