# Generated by Django 5.2.11 on 2026-07-17 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_menucategory_menuitem_menuitemimage_and_more'),
        ('orders', '0002_order_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='customization',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orderline',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.menuitem'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='kind',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('menu_item', 'Menu Item')], max_length=9),
        ),
    ]
