# Generated by Django 5.2.11 on 2026-07-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_user_order_orders_orde_email_46084d_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='service_variant',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='variant_label',
        ),
    ]
