# Generated by Django 5.2.11 on 2026-07-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_fulfilled_order_fulfilled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online (Stripe)'), ('in_store', 'Pay in store'), ('on_delivery', 'Pay on delivery'), ('terminal', 'Card terminal (POS)'), ('cash', 'Cash (POS)')], default='online', max_length=16),
        ),
    ]
