# Generated by Django 5.2.11 on 2026-08-03 20:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_service_booking_branches_and_more'),
        ('core', '0055_branch_booking_capacity_and_more'),
        ('orders', '0007_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, default='', max_length=255)),
                ('fulfillment', models.CharField(choices=[('branch', 'At the business location'), ('on_premises', "At the customer's address")], default='branch', max_length=16)),
                ('address', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('payment_option', models.CharField(choices=[('full', 'Paid in full on booking'), ('deposit', 'Deposit on booking'), ('in_person', 'Paid in person')], default='in_person', max_length=16)),
                ('deposit_percent', models.PositiveSmallIntegerField(default=0)),
                ('amount_due_now', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_due_later', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.branch')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='orders.order')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='catalog.service')),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['branch', 'starts_at'], name='orders_book_branch__06563d_idx'), models.Index(fields=['status', 'starts_at'], name='orders_book_status_e9fb1f_idx')],
            },
        ),
    ]
