# Generated by Django 5.2.11 on 2026-08-07 02:27

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=orders.models.order_qr_upload_path),
        ),
    ]
