# Generated by Django 5.2.11 on 2026-08-08 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_service_booking_party_enabled_and_more'),
        ('core', '0057_alter_branch_booking_capacity_resourcepool_and_more'),
        ('orders', '0009_order_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='party_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.bookingresource'),
        ),
        migrations.AddField(
            model_name='booking',
            name='resource_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['resource', 'starts_at'], name='orders_book_resourc_48475e_idx'),
        ),
    ]
