# Generated by Django 5.2.11 on 2026-08-14 17:31

import django.db.models.deletion
import django.db.models.functions.text
import orders.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_contactmessage_phone_and_more'),
        ('orders', '0010_booking_party_size_booking_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('percent', 'Percentage off'), ('fixed', 'Fixed amount off')], default='percent', max_length=8)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('MXN', 'Mexican Peso'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('ARS', 'Argentine Peso'), ('COP', 'Colombian Peso'), ('CLP', 'Chilean Peso'), ('BRL', 'Brazilian Real')], default='USD', max_length=3)),
                ('max_redemptions', models.PositiveIntegerField(default=0)),
                ('times_redeemed', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('enabled', models.BooleanField(default=True)),
                ('qr_code', models.ImageField(blank=True, max_length=255, null=True, upload_to=orders.models.coupon_qr_upload_path)),
                ('template_id', models.CharField(default='ticket', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='core.system')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['system', 'enabled'], name='orders_coup_system__6b63f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('code'), models.F('system'), name='coupon_code_unique_per_system'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='coupon_value_positive'),
        ),
    ]
