# Generated by Django 5.2.11 on 2026-08-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_coupon_code_order_discount_amount_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='brand_logo_background',
            field=models.CharField(choices=[('none', 'None'), ('circle', 'Circle'), ('square', 'Square'), ('rounded', 'Square with rounded corners (8px)'), ('triangle', 'Triangle'), ('pentagon', 'Pentagon'), ('hexagon', 'Hexagon'), ('octagon', 'Octagon'), ('logo', 'Logo silhouette (transparent logo)')], default='none', help_text="Shape of the plate behind the brand logo. 'None' draws the logo bare.", max_length=16),
        ),
        migrations.AddField(
            model_name='coupon',
            name='brand_logo_background_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='Logo-with-background size as a whole percent (30-100).'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='brand_logo_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='Logo size inside its background, as a whole percent (30-100).'),
        ),
    ]
