# Generated by Django 5.2.11 on 2026-08-17 07:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_coupon_brand_logo_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='size_en_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderline',
            name='size_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderline',
            name='size_price_delta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
