# Generated by Django 5.2.11 on 2026-08-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_homepageflyer'),
        ('orders', '0013_orderline_size_en_name_orderline_size_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='scope_id',
            field=models.PositiveIntegerField(blank=True, help_text="The id of the targeted item or category, within `scope_kind`'s own table.", null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='scope_kind',
            field=models.CharField(blank=True, choices=[('', 'The whole order'), ('product', 'One product'), ('service', 'One service'), ('menu_item', 'One menu item'), ('product_category', 'A product category'), ('service_category', 'A service category'), ('menu_category', 'A menu category')], default='', help_text='What the discount applies to. Blank means the whole order.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_id__isnull', True), ('scope_kind', '')), models.Q(models.Q(('scope_kind', ''), _negated=True), ('scope_id__isnull', False)), _connector='OR'), name='coupon_scope_kind_and_id_together'),
        ),
    ]
