# Generated by Django 5.2.11 on 2026-08-20 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_system_rewards_enabled'),
        ('orders', '0014_coupon_scope_id_coupon_scope_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='points_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderline',
            name='paid_with_points',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderline',
            name='points_award',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderline',
            name='points_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('kind', models.CharField(choices=[('earn', 'Earned on a purchase'), ('spend', 'Spent on a purchase'), ('release', 'Returned from an abandoned order'), ('revoke', 'Taken back from a canceled order'), ('adjust', 'Manual adjustment')], max_length=8)),
                ('points', models.IntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='orders.order')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='core.system')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Points Transaction',
                'verbose_name_plural': 'Points Transactions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['system', 'user', '-created_at'], name='orders_poin_system__110b3c_idx'), models.Index(fields=['system', 'email'], name='orders_poin_system__ab4f6c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('points', 0), _negated=True), name='points_transaction_nonzero'), models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('email', ''), _negated=True), _connector='OR'), name='points_transaction_has_owner')],
            },
        ),
        migrations.CreateModel(
            name='RewardTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('en_name', models.CharField(blank=True, default='', max_length=64)),
                ('threshold', models.PositiveIntegerField(default=0, help_text='Points earned within the period below to reach and keep this tier.')),
                ('period_months', models.PositiveSmallIntegerField(default=12, help_text='How many months of earnings count toward the threshold.')),
                ('earn_multiplier', models.PositiveSmallIntegerField(default=100, help_text="Points earned as a whole percent of the item's award (100 = normal).")),
                ('color', models.CharField(blank=True, default='', max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_tiers', to='core.system')),
            ],
            options={
                'verbose_name': 'Reward Tier',
                'verbose_name_plural': 'Reward Tiers',
                'ordering': ['threshold', 'id'],
                'constraints': [models.UniqueConstraint(fields=('system', 'threshold'), name='reward_tier_threshold_unique_per_system')],
            },
        ),
    ]
