# Generated by Django 5.2.11 on 2026-08-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_menucategory_points_award_menuitem_points_award_and_more'),
        ('orders', '0015_order_points_earned_order_points_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='menu_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='catalog.menusize'),
        ),
    ]
