# Generated by Django 5.2.11 on 2026-08-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderline_menu_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='linked_by_email',
            field=models.BooleanField(default=False),
        ),
    ]
