# Generated by Django 4.1.9 on 2023-06-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000, help_text='Anio del vehiculo', verbose_name='Anio del vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiclemake',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
