# Generated by Django 5.2.11 on 2026-03-02 06:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('site_name', models.CharField(default='Web Site', max_length=32)),
                ('host', models.CharField(default='127.0.0.1', max_length=64, unique=True)),
                ('img_logo', models.ImageField(blank=True, null=True, upload_to=core.models.picture)),
                ('img_logo_hero', models.ImageField(blank=True, null=True, upload_to=core.models.picture)),
                ('img_favicon', models.ImageField(blank=True, null=True, upload_to=core.models.picture)),
                ('img_manifest_1080', models.ImageField(blank=True, null=True, upload_to=core.models.picture)),
                ('img_manifest_512', models.ImageField(blank=True, null=True, upload_to=core.models.picture)),
                ('img_manifest_256', models.ImageField(blank=True, null=True, upload_to=core.models.picture)),
                ('img_manifest_128', models.ImageField(blank=True, null=True, upload_to=core.models.picture)),
                ('video_link', models.URLField(blank=True, max_length=255, null=True)),
                ('primary_color', models.CharField(default='#2196f3', max_length=16)),
                ('secondary_color', models.CharField(default='#e040fb', max_length=16)),
                ('about', models.TextField(blank=True, null=True)),
                ('en_about', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('en_mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('en_vision', models.TextField(blank=True, null=True)),
                ('img_about', models.ImageField(blank=True, null=True, upload_to=core.models.picture)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
                ('en_privacy_policy', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('en_terms_and_conditions', models.TextField(blank=True, null=True)),
                ('user_data', models.TextField(blank=True, null=True)),
                ('en_user_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
            },
        ),
    ]
