# Generated by Django 5.2.11 on 2026-03-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='brand', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
