# Generated by Django 5.2.11 on 2026-03-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_system_img_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='slogan',
            field=models.CharField(blank=True, default='Company slogan', max_length=255, null=True),
        ),
    ]
