# Generated by Django 5.2.11 on 2026-03-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companyhighlight_companyhighlightitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyhighlight',
            name='size',
            field=models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large'), ('xl', 'Extra Large')], default='md', max_length=4),
        ),
    ]
