# Generated by Django 5.2.11 on 2026-03-23 21:59

import core.fields
import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_system_catalog_items_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhighlight',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[512, None], null=True, quality=90, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[512, None], null=True, quality=90, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='successstoryimage',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[512, None], null=True, quality=90, upload_to=core.models.picture),
        ),
    ]
