# Generated by Django 5.2.11 on 2026-03-24 15:49

import core.fields
import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_successstory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhighlight',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[1200, None], null=True, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[1200, None], null=True, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='successstoryimage',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[1200, None], null=True, upload_to=core.models.picture),
        ),
    ]
