# Generated by Django 5.2.11 on 2026-03-26 18:03

import core.fields
import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_successstoryimage_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstoryimage',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[900, None], null=True, upload_to=core.models.picture),
        ),
    ]
