# Generated by Django 5.2.11 on 2026-04-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_highlights_en_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='en_site_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='site_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
