# Generated by Django 5.2.11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_system_site_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='img_manifest_192',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.picture),
        ),
    ]
