# Generated by Django 5.2.11 on 2026-07-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_system_img_manifest_192'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='stripe_enabled',
            field=models.BooleanField(default=False, help_text='Whether this site can take payments. Checkout refuses unless this is on AND both Stripe secrets are set.'),
        ),
        migrations.AddField(
            model_name='system',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='system',
            name='stripe_secret_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='system',
            name='stripe_webhook_secret_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
