# Generated by Django 5.2.11 on 2026-07-18 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_system_stripe_webhook_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='core.system'),
        ),
        migrations.AlterField(
            model_name='companyhighlight',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='core.system'),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='success_stories', to='core.system'),
        ),
    ]
