# Generated by Django 5.2.11 on 2026-07-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_brand_system_alter_companyhighlight_system_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='successstory',
            options={'ordering': ['sort_order', '-created'], 'verbose_name': 'Success Story', 'verbose_name_plural': 'Success Stories'},
        ),
        migrations.AddField(
            model_name='brand',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='successstory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
