# Generated by Django 5.2.11 on 2026-07-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_brand_options_alter_successstory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='background_dark',
            field=models.CharField(default='#3c3c3c', help_text='Page background color in the dark theme.', max_length=16),
        ),
        migrations.AddField(
            model_name='system',
            name='background_light',
            field=models.CharField(default='#e5e5e5', help_text='Page background color in the light theme.', max_length=16),
        ),
        migrations.AddField(
            model_name='system',
            name='watermark_enabled',
            field=models.BooleanField(default=False, help_text="Tile this site's logo faintly behind every public page."),
        ),
        migrations.AddField(
            model_name='system',
            name='watermark_opacity',
            field=models.PositiveSmallIntegerField(default=4, help_text='Opacity of the pattern as a whole percent (1-25).'),
        ),
        migrations.AddField(
            model_name='system',
            name='watermark_rotation',
            field=models.SmallIntegerField(default=-12, help_text='Rotation of the tiled pattern in degrees (-45 to 45).'),
        ),
        migrations.AddField(
            model_name='system',
            name='watermark_size',
            field=models.PositiveSmallIntegerField(default=120, help_text='Drawn width of one logo in px.'),
        ),
        migrations.AddField(
            model_name='system',
            name='watermark_spacing',
            field=models.PositiveSmallIntegerField(default=70, help_text='Empty space between logos in px (added to the tile size).'),
        ),
    ]
