# Generated by Django 5.2.11 on 2026-07-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_system_background_dark_system_background_light_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='hero_video_layout',
            field=models.CharField(choices=[('default', 'Default - logo and text over the video'), ('profile', 'Profile - logo in a circle on the bottom edge')], default='default', help_text='How the logo and text are laid out over the hero video.', max_length=16),
        ),
    ]
