# Generated by Django 5.2.11 on 2026-07-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_system_hero_video_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='hero_logo_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='Profile-layout logo size inside the circle, as a whole percent (50-100).'),
        ),
    ]
