# Generated by Django 5.2.11 on 2026-07-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_system_hero_logo_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='hero_logo_background_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='Background badge size, as a whole percent of its default diameter (50-100).'),
        ),
        migrations.AlterField(
            model_name='system',
            name='hero_logo_background',
            field=models.CharField(choices=[('none', 'None'), ('circle', 'Circle'), ('square', 'Square'), ('rounded', 'Square with rounded corners (8px)'), ('triangle', 'Triangle'), ('pentagon', 'Pentagon'), ('hexagon', 'Hexagon'), ('octagon', 'Octagon'), ('logo', 'Logo silhouette (transparent logo)')], default='none', help_text="Shape drawn behind the hero logo, in either layout. 'None' draws the logo plain.", max_length=16),
        ),
    ]
