# Generated by Django 5.2.11 on 2026-07-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_system_hero_logo_background_scale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='watermark_intercalated',
            field=models.BooleanField(default=False, help_text="Alternate each logo's rotation so neighbours lean opposite ways."),
        ),
    ]
