# Generated by Django 5.2.11 on 2026-07-21 16:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_system_watermark_intercalated'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='font_body',
            field=models.CharField(blank=True, default='', help_text="CSS family name for body text, e.g. 'Karla'. Must be loaded by the URL above.", max_length=64),
        ),
        migrations.AddField(
            model_name='system',
            name='font_display',
            field=models.CharField(blank=True, default='', help_text="CSS family name for headings, e.g. 'Fraunces'. Must be loaded by the URL above.", max_length=64),
        ),
        migrations.AddField(
            model_name='system',
            name='google_font_url',
            field=models.URLField(blank=True, default='', help_text="Google Fonts stylesheet URL loading this site's typefaces, e.g. https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,300..700&family=Karla:wght@400;500;700&display=swap. Blank keeps the default font.", max_length=512, validators=[core.models.validate_google_font_url]),
        ),
    ]
