# Generated by Django 5.2.11 on 2026-07-21 21:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_system_hero_overlay_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='img_brandmark',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.picture),
        ),
        migrations.AddField(
            model_name='system',
            name='watermark_use_brandmark',
            field=models.BooleanField(default=False, help_text='Tile the brandmark instead of the logo in the page watermark (needs a brandmark image).'),
        ),
        migrations.AlterField(
            model_name='system',
            name='hero_video_layout',
            field=models.CharField(choices=[('default', 'Default - logo and text over the video'), ('none', 'None - text and buttons only, no logo over the video'), ('profile', 'Profile - logo in a circle on the bottom edge')], default='default', help_text='How the logo and text are laid out over the hero video.', max_length=16),
        ),
    ]
