# Generated by Django 5.2.11 on 2026-07-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_system_img_brandmark_system_watermark_use_brandmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='hero_text_frame',
            field=models.BooleanField(default=False, help_text='Wrap the hero section/page heading in an outline frame (with the brandmark badge if set).'),
        ),
    ]
