# Generated by Django 5.2.11 on 2026-07-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_system_hero_text_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='hero_overlay_extent',
            field=models.PositiveSmallIntegerField(default=50, help_text='How far the gradient overlay reaches across the frame, as a whole percent (0-100); 50 is the default reach.'),
        ),
    ]
