# Generated by Django 5.2.11 on 2026-07-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_system_hero_overlay_extent'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='pay_in_store_enabled',
            field=models.BooleanField(default=False, help_text='Let customers place an order to pay when they pick it up in store.'),
        ),
        migrations.AddField(
            model_name='system',
            name='pay_on_delivery_enabled',
            field=models.BooleanField(default=False, help_text='Let customers place an order to pay on delivery (collects a delivery address).'),
        ),
    ]
