# Generated by Django 5.2.11 on 2026-07-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_system_spotlight_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='spotlight_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
