# Generated by Django 5.2.11 on 2026-07-23 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_contactmessage_replied_at_contactmessage_replied_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('related_kind', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('food', 'Menu item')], max_length=16)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('template_id', models.CharField(max_length=64)),
                ('format', models.CharField(choices=[('1x1', 'Square 1:1'), ('4x5', 'Portrait 4:5')], default='1x1', max_length=8)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('image_text', models.TextField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('include_item_data', models.BooleanField(default=True, help_text="Overlay the item's price (and discount, if any) on the flyer.")),
                ('include_brand', models.BooleanField(default=True, help_text='Overlay the brand logo and slogan on the flyer.')),
                ('include_hashtags', models.BooleanField(default=True, help_text='Show the LLM-suggested hashtags beneath the post caption.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='core.system')),
            ],
            options={
                'verbose_name': 'Social Post',
                'verbose_name_plural': 'Social Posts',
                'ordering': ['sort_order', '-created'],
            },
        ),
    ]
