# Generated by Django 5.2.11 on 2026-07-23 22:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_socialpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='badge_image_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='Photo size inside the badge, as a whole percent (30-100).'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='badge_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='Badge size as a whole percent of its default size (30-100).'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='badge_shape',
            field=models.CharField(choices=[('none', 'None'), ('circle', 'Circle'), ('square', 'Square'), ('rounded', 'Square with rounded corners (8px)'), ('triangle', 'Triangle'), ('pentagon', 'Pentagon'), ('hexagon', 'Hexagon'), ('octagon', 'Octagon'), ('logo', 'Logo silhouette (transparent logo)')], default='circle', help_text="Shape framing the centred item photo. 'None' draws the photo unframed.", max_length=16),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='img_background',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.picture),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='img_item',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.picture),
        ),
    ]
