# Generated by Django 5.2.11 on 2026-07-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_socialpost_brand_logo_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='hero_logo_background_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='Background badge size, as a whole percent of its default diameter (30-100).'),
        ),
        migrations.AlterField(
            model_name='system',
            name='hero_logo_scale',
            field=models.PositiveSmallIntegerField(default=100, help_text='Logo size inside the background shape, as a whole percent (30-100).'),
        ),
    ]
