# Generated by Django 5.2.11 on 2026-07-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_system_hero_logo_background_scale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='hero_bottom_divider',
            field=models.CharField(choices=[('none', 'None - hard edge'), ('wave', 'Wave - organic wave'), ('scallop', 'Half-circles - scalloped edge'), ('zigzag', 'Zigzag - triangular bunting'), ('spikes', 'Spikes - fine sawtooth'), ('arches', 'Arches - smooth wide humps'), ('slant', 'Slant - straight diagonal')], default='none', help_text="Shape of the transparent notch cut into the hero's bottom edge (page shows through).", max_length=16),
        ),
    ]
