# Generated by Django 5.2.11 on 2026-07-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_system_hero_bottom_divider'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='hero_bottom_divider_elevation',
            field=models.PositiveSmallIntegerField(default=10, help_text="Depth of the divider edge's drop-shadow, on the 0-24 elevation scale."),
        ),
    ]
