# Generated by Django 5.2.11 on 2026-07-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_system_hero_bottom_divider_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='catalog_bottom_divider',
            field=models.CharField(choices=[('none', 'None - hard edge'), ('wave', 'Wave - organic wave'), ('scallop', 'Half-circles - scalloped edge'), ('zigzag', 'Zigzag - triangular bunting'), ('spikes', 'Spikes - fine sawtooth'), ('arches', 'Arches - smooth wide humps'), ('slant', 'Slant - straight diagonal')], default='none', help_text='Shape of the notch cut into the bottom edge of the Catalog Items band.', max_length=16),
        ),
        migrations.AddField(
            model_name='system',
            name='catalog_top_divider',
            field=models.CharField(choices=[('none', 'None - hard edge'), ('wave', 'Wave - organic wave'), ('scallop', 'Half-circles - scalloped edge'), ('zigzag', 'Zigzag - triangular bunting'), ('spikes', 'Spikes - fine sawtooth'), ('arches', 'Arches - smooth wide humps'), ('slant', 'Slant - straight diagonal')], default='none', help_text='Shape of the notch cut into the top edge of the Catalog Items band.', max_length=16),
        ),
        migrations.AddField(
            model_name='system',
            name='highlights_bottom_divider',
            field=models.CharField(choices=[('none', 'None - hard edge'), ('wave', 'Wave - organic wave'), ('scallop', 'Half-circles - scalloped edge'), ('zigzag', 'Zigzag - triangular bunting'), ('spikes', 'Spikes - fine sawtooth'), ('arches', 'Arches - smooth wide humps'), ('slant', 'Slant - straight diagonal')], default='none', help_text='Shape of the notch cut into the bottom edge of the Company Highlights band.', max_length=16),
        ),
        migrations.AddField(
            model_name='system',
            name='highlights_top_divider',
            field=models.CharField(choices=[('none', 'None - hard edge'), ('wave', 'Wave - organic wave'), ('scallop', 'Half-circles - scalloped edge'), ('zigzag', 'Zigzag - triangular bunting'), ('spikes', 'Spikes - fine sawtooth'), ('arches', 'Arches - smooth wide humps'), ('slant', 'Slant - straight diagonal')], default='none', help_text='Shape of the notch cut into the top edge of the Company Highlights band.', max_length=16),
        ),
    ]
