# Generated by Django 5.2.11 on 2026-07-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_system_catalog_bottom_divider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='catalog_bottom_divider',
            field=models.CharField(choices=[('none', 'None - hard edge'), ('wave', 'Wave - organic wave'), ('scallop', 'Half-circles - scalloped edge'), ('zigzag', 'Zigzag - triangular bunting'), ('spikes', 'Spikes - fine sawtooth'), ('arches', 'Arches - smooth wide humps'), ('slant', 'Slant - straight diagonal'), ('inverted-slant', 'Inverted slant - the same diagonal, mirrored')], default='none', help_text='Shape of the notch cut into the bottom edge of the Catalog Items band.', max_length=16),
        ),
        migrations.AlterField(
            model_name='system',
            name='catalog_top_divider',
            field=models.CharField(choices=[('none', 'None - hard edge'), ('wave', 'Wave - organic wave'), ('scallop', 'Half-circles - scalloped edge'), ('zigzag', 'Zigzag - triangular bunting'), ('spikes', 'Spikes - fine sawtooth'), ('arches', 'Arches - smooth wide humps'), ('slant', 'Slant - straight diagonal'), ('inverted-slant', 'Inverted slant - the same diagonal, mirrored')], default='none', help_text='Shape of the notch cut into the top edge of the Catalog Items band.', max_length=16),
        ),
        migrations.AlterField(
            model_name='system',
            name='hero_bottom_divider',
            field=models.CharField(choices=[('none', 'None - hard edge'), ('wave', 'Wave - organic wave'), ('scallop', 'Half-circles - scalloped edge'), ('zigzag', 'Zigzag - triangular bunting'), ('spikes', 'Spikes - fine sawtooth'), ('arches', 'Arches - smooth wide humps'), ('slant', 'Slant - straight diagonal'), ('inverted-slant', 'Inverted slant - the same diagonal, mirrored')], default='none', help_text="Shape of the transparent notch cut into the hero's bottom edge (page shows through).", max_length=16),
        ),
        migrations.AlterField(
            model_name='system',
            name='highlights_bottom_divider',
            field=models.CharField(choices=[('none', 'None - hard edge'), ('wave', 'Wave - organic wave'), ('scallop', 'Half-circles - scalloped edge'), ('zigzag', 'Zigzag - triangular bunting'), ('spikes', 'Spikes - fine sawtooth'), ('arches', 'Arches - smooth wide humps'), ('slant', 'Slant - straight diagonal'), ('inverted-slant', 'Inverted slant - the same diagonal, mirrored')], default='none', help_text='Shape of the notch cut into the bottom edge of the Company Highlights band.', max_length=16),
        ),
        migrations.AlterField(
            model_name='system',
            name='highlights_top_divider',
            field=models.CharField(choices=[('none', 'None - hard edge'), ('wave', 'Wave - organic wave'), ('scallop', 'Half-circles - scalloped edge'), ('zigzag', 'Zigzag - triangular bunting'), ('spikes', 'Spikes - fine sawtooth'), ('arches', 'Arches - smooth wide humps'), ('slant', 'Slant - straight diagonal'), ('inverted-slant', 'Inverted slant - the same diagonal, mirrored')], default='none', help_text='Shape of the notch cut into the top edge of the Company Highlights band.', max_length=16),
        ),
    ]
