# Generated by Django 5.2.11 on 2026-07-27 19:56

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_system_catalog_bottom_divider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=255, upload_to=core.models.backup_upload_path)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('include_images', models.BooleanField(default=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('media_files', models.PositiveIntegerField(default=0)),
                ('record_counts', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_backups', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='core.system')),
            ],
            options={
                'verbose_name': 'Site Backup',
                'verbose_name_plural': 'Site Backups',
                'ordering': ['-created'],
            },
        ),
    ]
