# Generated by Django 5.2.11 on 2026-07-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_sitebackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='storage_access_key_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='system',
            name='storage_account_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='system',
            name='storage_bucket_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='system',
            name='storage_enabled',
            field=models.BooleanField(default=False, help_text="Store this site's images and backups in its own Cloudflare R2 bucket instead of the platform's."),
        ),
        migrations.AddField(
            model_name='system',
            name='storage_public_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='system',
            name='storage_secret_access_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
