# Generated by Django 5.2.11 on 2026-08-03 20:59

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_system_storage_access_key_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='booking_capacity',
            field=models.PositiveIntegerField(default=1, help_text='How many bookings may overlap at this location (staff, chairs, rooms).'),
        ),
        migrations.AddField(
            model_name='branch',
            name='booking_max_days_ahead',
            field=models.PositiveIntegerField(default=60, help_text='How far ahead the booking calendar goes.'),
        ),
        migrations.AddField(
            model_name='branch',
            name='booking_min_notice_hours',
            field=models.PositiveIntegerField(default=2, help_text='Minimum hours between now and the start of a bookable slot.'),
        ),
        migrations.AddField(
            model_name='branch',
            name='booking_slot_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minutes between offered start times (the booking grid).'),
        ),
        migrations.AddField(
            model_name='branch',
            name='timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone name (e.g. America/Mexico_City). Opening hours are local to this.', max_length=64, validators=[core.models.validate_timezone]),
        ),
        migrations.CreateModel(
            name='BranchHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='core.branch')),
            ],
            options={
                'verbose_name': 'Branch hours',
                'verbose_name_plural': 'Branch hours',
                'ordering': ['branch', 'weekday'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'weekday'), name='branch_hours_unique_weekday')],
            },
        ),
    ]
