# Generated by Django 5.2.11 on 2026-08-05 21:32

import colorfield.fields
import core.fields
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_branch_booking_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('en_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('en_description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('en_short_description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('fit', models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('image', core.fields.ResizedImageField(blank=True, max_size=[1200, None], null=True, upload_to=core.models.picture)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('en_venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('starts_at', models.DateTimeField(help_text='When the event begins.')),
                ('ends_at', models.DateTimeField(blank=True, help_text='When it finishes. Blank for an event with no announced end.', null=True)),
                ('is_all_day', models.BooleanField(default=False, help_text='Show the date without a time (an open day, a week-long fair).')),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone the times above are local to (e.g. America/Mexico_City).', max_length=64, validators=[core.models.validate_timezone])),
                ('is_featured', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, help_text="One of the business's own locations. Leave empty to name a one-off place below.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.branch')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.system')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('en_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('en_description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('en_short_description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('fit', models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('image', core.fields.ResizedImageField(blank=True, max_size=[900, None], null=True, upload_to=core.models.picture)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.event')),
            ],
            options={
                'verbose_name': 'Event Image',
                'verbose_name_plural': 'Event Images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['system', 'starts_at'], name='core_event_system_start'),
        ),
    ]
