# Generated by Django 5.2.11 on 2026-08-08 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_event_eventimage_event_core_event_system_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='booking_capacity',
            field=models.PositiveIntegerField(default=1, help_text='How many people can be booked into the same time here (seats, chairs, places). Ignored once this location defines resource pools - their capacities are used instead.'),
        ),
        migrations.CreateModel(
            name='ResourcePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('en_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_label', models.CharField(blank=True, help_text='What one of these is called, singular: "boat", "guide", "table".', max_length=64, null=True)),
                ('en_unit_label', models.CharField(blank=True, max_length=64, null=True)),
                ('customer_selectable', models.BooleanField(default=False, help_text='Let the customer pick a specific one when booking.')),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_pools', to='core.branch')),
            ],
            options={
                'verbose_name': 'Resource pool',
                'verbose_name_plural': 'Resource pools',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='BookingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('en_name', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.PositiveIntegerField(default=1, help_text='How many people this one holds.')),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.resourcepool')),
            ],
            options={
                'verbose_name': 'Booking resource',
                'verbose_name_plural': 'Booking resources',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
