# Generated by Django 5.2.11 on 2026-08-08 17:19

from django.db import migrations, models

# What every existing row carried, and what a reverse run has to put back.
LEGACY_GRID_MINUTES = 30


def clear_grid(apps, schema_editor):
    """Hand every existing branch back to "follow the service's duration".

    The column used to default to 30 and nothing in the CMS explained it, so a
    stored 30 is the default nobody chose rather than a decision worth keeping -
    and leaving it in place would mean the new behaviour only ever reached
    branches created after this migration. A location that really does want
    starts every half hour types 30 back into the field, which is now an explicit
    override with a label that says so.
    """
    apps.get_model("core", "Branch").objects.update(booking_slot_minutes=None)


def restore_grid(apps, schema_editor):
    """Reverse: put the old fixed grid back on every row.

    The column is about to become NOT NULL again, so nulls cannot simply stay -
    and 30 is exactly what the field defaulted to before this migration.
    """
    Branch = apps.get_model("core", "Branch")
    Branch.objects.filter(booking_slot_minutes__isnull=True).update(
        booking_slot_minutes=LEGACY_GRID_MINUTES
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_branch_booking_capacity_resourcepool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='booking_slot_minutes',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="Minutes between offered start times. Leave empty to space them by each service's own duration.", null=True),
        ),
        migrations.RunPython(clear_grid, restore_grid),
    ]
