# Generated by Django 5.2.11 on 2026-08-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_branch_booking_slot_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='map_attribution',
            field=models.CharField(blank=True, default='', help_text="Only used when the style is 'Custom'. The credit drawn in the map's corner - required by every tile provider. Left blank, the OpenStreetMap credit is used.", max_length=200),
        ),
        migrations.AddField(
            model_name='system',
            name='map_attribution_url',
            field=models.URLField(blank=True, default='', help_text="Only used when the style is 'Custom'. Where the credit links - most providers require it to point back at them, e.g. https://www.maptiler.com/copyright/ . Left blank, the credit is drawn as plain text.", max_length=300),
        ),
        migrations.AddField(
            model_name='system',
            name='map_style',
            field=models.CharField(choices=[('osm', 'OpenStreetMap standard'), ('carto-light', 'CARTO Positron (pale)'), ('carto-dark', 'CARTO Dark Matter'), ('carto-voyager', 'CARTO Voyager'), ('custom', 'Custom tile server')], default='osm', help_text="Which basemap this site's maps are drawn from. 'Custom' uses the tile URL below - a provider needing an API key (MapTiler, Mapbox, Thunderforest), or a tile server of your own.", max_length=32),
        ),
        migrations.AddField(
            model_name='system',
            name='map_tile_url',
            field=models.CharField(blank=True, default='', help_text="Only used when the style is 'Custom'. A {z}/{x}/{y} template, e.g. https://api.maptiler.com/maps/streets-v2/{z}/{x}/{y}.png?key=YOUR_KEY", max_length=500),
        ),
    ]
