# Generated by Django 5.2.11 on 2026-08-08 21:52

import core.fields
import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_system_map_attribution_system_map_attribution_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='map_image',
            field=core.fields.ResizedImageField(blank=True, help_text='Map screenshot rendered by the CMS map picker. Emailed with a booking.', max_size=[900, None], null=True, upload_to=core.models.branch_map_upload_path),
        ),
    ]
