# Generated by Django 5.2.11 on 2026-08-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_branch_booking_slot_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location_details',
            field=models.TextField(blank=True, help_text='How to find the entrance once you are there (landmarks, floor, parking). Shown under the map and sent in booking emails.', null=True),
        ),
    ]
