# Generated by Django 5.2.11 on 2026-08-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_branch_location_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='en_location_details',
            field=models.TextField(blank=True, help_text='English version of the location details. Shown to readers on the English site; the Spanish one is used when this is blank.', null=True),
        ),
    ]
