# Generated by Django 5.2.11 on 2026-08-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_branch_en_location_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='preferred_channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=16),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_channel',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
