# Generated by Django 5.2.11 on 2026-08-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_contactmessage_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='en_kind_label_appetizer',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='en_kind_label_dessert',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='en_kind_label_drink',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='en_kind_label_food',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='en_kind_label_product',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='en_kind_label_service',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='en_kind_label_side',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='kind_label_appetizer',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='kind_label_dessert',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='kind_label_drink',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='kind_label_food',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='kind_label_product',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='kind_label_service',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='kind_label_side',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
