# Generated by Django 5.2.11 on 2026-08-19 22:29

import colorfield.fields
import core.fields
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_companyhighlight_attribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('en_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('en_description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('en_short_description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('attribution', models.CharField(blank=True, default='', max_length=255)),
                ('attribution_url', models.URLField(blank=True, default='', max_length=500)),
                ('fit', models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('image', core.fields.ResizedImageField(blank=True, max_size=[1200, None], null=True, upload_to=core.models.picture)),
                ('items', models.JSONField(blank=True, default=list, help_text='Ordered refs of the featured items, e.g. [{"kind": "product", "id": 12}]. Max 3.')),
                ('image_side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', help_text='Which side the photograph sits on from the sm breakpoint up.', max_length=8)),
                ('background', models.TextField(blank=True, help_text="CSS background painted behind this flyer's slide. Blank = no band.", null=True)),
                ('top_divider', models.CharField(choices=[('none', 'None - hard edge'), ('wave', 'Wave - organic wave'), ('scallop', 'Half-circles - scalloped edge'), ('zigzag', 'Zigzag - triangular bunting'), ('spikes', 'Spikes - fine sawtooth'), ('arches', 'Arches - smooth wide humps'), ('slant', 'Slant - straight diagonal'), ('inverted-slant', 'Inverted slant - the same diagonal, mirrored')], default='none', help_text="Shape of the notch cut into the top edge of this flyer's band.", max_length=16)),
                ('bottom_divider', models.CharField(choices=[('none', 'None - hard edge'), ('wave', 'Wave - organic wave'), ('scallop', 'Half-circles - scalloped edge'), ('zigzag', 'Zigzag - triangular bunting'), ('spikes', 'Spikes - fine sawtooth'), ('arches', 'Arches - smooth wide humps'), ('slant', 'Slant - straight diagonal'), ('inverted-slant', 'Inverted slant - the same diagonal, mirrored')], default='none', help_text="Shape of the notch cut into the bottom edge of this flyer's band.", max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_flyers', to='core.system')),
            ],
            options={
                'verbose_name': 'Homepage Flyer',
                'verbose_name_plural': 'Homepage Flyers',
                'ordering': ['sort_order', '-created'],
            },
        ),
    ]
