# Generated by Django 5.2.11 on 2026-08-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_homepageflyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='rewards_enabled',
            field=models.BooleanField(default=False, help_text='Turn the rewards program on. Off, nothing earns or spends points.'),
        ),
    ]
