# Generated by Django 5.2.11 on 2026-08-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_system_points_per_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='navbar_translucent',
            field=models.BooleanField(default=True, help_text='Make the navbar semi-transparent with a backdrop blur (off = a solid bar).'),
        ),
    ]
