# Generated by Django 5.2.11 on 2026-08-22 17:36

from django.db import migrations, models


"""Drop `site_prefix`'s literal default; `System.save()` derives it instead.

A `default=` on a `unique=True` column is one string every row would share, so
the second `System.objects.create(host=...)` on a database failed the insert.
The value now comes from the row's own host in `System.save()`, which covers the
doors a serializer validator never sees - a fixture, the Django admin, a test, a
shell one-liner.

Schema-only: `0072` already back-filled every existing row, and none of them
carry the old default.
"""

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_system_site_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='site_prefix',
            field=models.SlugField(blank=True, default='', max_length=32, unique=True),
        ),
    ]
