# Generated by Django 5.2.11 on 2026-08-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_system_site_prefix_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyhighlight',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='companyhighlightitem',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='homepageflyer',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='successstory',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='successstoryimage',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
    ]
