{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cinelog-api.fullname" . }}-redis
  labels:
    {{- include "cinelog-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cinelog-api.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "cinelog-api.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          {{- if .Values.redis.auth.password }}
          command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
          env:
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.auth.password | quote }}
          {{- end }}
          ports:
            - containerPort: 6379
          livenessProbe:
            exec:
              command:
                {{- if .Values.redis.auth.password }}
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
                {{- else }}
                - redis-cli
                - ping
                {{- end }}
            periodSeconds: 10
            failureThreshold: 3
          {{- with .Values.redis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "cinelog-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "cinelog-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: 6379
      targetPort: 6379
{{- end }}
