# Generated by Django 4.1.9 on 2023-06-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=2000, help_text='Anio del inmueble', null=True, verbose_name='Anio del inmueble'),
        ),
    ]
