# Generated by Django 4.1.9 on 2024-01-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_alter_realestate_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realestateclassification',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realestatefeature',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realestatepicture',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
