# Generated by Django 5.2.11 on 2026-07-16 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_video_link_service_video_link'),
        ('core', '0022_system_img_manifest_192'),
        ('users', '0006_passkeycredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalog.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalog.service')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to='core.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('user', 'product'), name='unique_user_product_favorite'), models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('user', 'service'), name='unique_user_service_favorite'), models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('service__isnull', True)), models.Q(('product__isnull', True), ('service__isnull', False)), _connector='OR'), name='favorite_exactly_one_target')],
            },
        ),
    ]
