# Generated by Django 5.2.11 on 2026-07-16 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_video_link_service_video_link'),
        ('core', '0022_system_img_manifest_192'),
        ('users', '0007_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.product')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.productvariant')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.service')),
                ('service_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.servicevariant')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='core.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('product__isnull', False), ('product_variant__isnull', False)), fields=('user', 'product', 'product_variant'), name='unique_user_product_variant_cart_item'), models.UniqueConstraint(condition=models.Q(('product__isnull', False), ('product_variant__isnull', True)), fields=('user', 'product'), name='unique_user_product_cart_item'), models.UniqueConstraint(condition=models.Q(('service__isnull', False), ('service_variant__isnull', False)), fields=('user', 'service', 'service_variant'), name='unique_user_service_variant_cart_item'), models.UniqueConstraint(condition=models.Q(('service__isnull', False), ('service_variant__isnull', True)), fields=('user', 'service'), name='unique_user_service_cart_item'), models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('service__isnull', True)), models.Q(('product__isnull', True), ('service__isnull', False)), _connector='OR'), name='cart_item_exactly_one_target'), models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('service_variant__isnull', True)), models.Q(('product_variant__isnull', True), ('service__isnull', False)), _connector='OR'), name='cart_item_variant_matches_target'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='cart_item_quantity_positive')],
            },
        ),
    ]
