# Generated by Django 5.2.11 on 2026-07-17 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_menucategory_menuitem_menuitemimage_and_more'),
        ('core', '0024_system_stripe_webhook_token'),
        ('users', '0008_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='cart_item_exactly_one_target',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='cart_item_variant_matches_target',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='customization',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.menuitem'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('menu_item__isnull', True), ('product__isnull', False), ('service__isnull', True)), models.Q(('menu_item__isnull', True), ('product__isnull', True), ('service__isnull', False)), models.Q(('menu_item__isnull', False), ('product__isnull', True), ('service__isnull', True)), _connector='OR'), name='cart_item_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('service_variant__isnull', True)), models.Q(('product_variant__isnull', True), ('service__isnull', False)), models.Q(('menu_item__isnull', False), ('product_variant__isnull', True), ('service_variant__isnull', True)), _connector='OR'), name='cart_item_variant_matches_target'),
        ),
    ]
