# Generated by Django 5.2.11 on 2026-07-17 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_menuitem_is_organic'),
        ('core', '0024_system_stripe_webhook_token'),
        ('users', '0009_remove_cartitem_cart_item_exactly_one_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='favorite_exactly_one_target',
        ),
        migrations.AddField(
            model_name='favorite',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalog.menuitem'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('menu_item__isnull', False)), fields=('user', 'menu_item'), name='unique_user_menu_item_favorite'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('menu_item__isnull', True), ('product__isnull', False), ('service__isnull', True)), models.Q(('menu_item__isnull', True), ('product__isnull', True), ('service__isnull', False)), models.Q(('menu_item__isnull', False), ('product__isnull', True), ('service__isnull', True)), _connector='OR'), name='favorite_exactly_one_target'),
        ),
    ]
