# Generated by Django 5.2.11 on 2026-07-20 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_remove_productvariant_option_values_and_more'),
        ('core', '0027_system_background_dark_system_background_light_and_more'),
        ('users', '0010_remove_favorite_favorite_exactly_one_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_user_product_variant_cart_item',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_user_product_cart_item',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_user_service_variant_cart_item',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_user_service_cart_item',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='cart_item_variant_matches_target',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='service_variant',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('user', 'product'), name='unique_user_product_cart_item'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('user', 'service'), name='unique_user_service_cart_item'),
        ),
    ]
