# Generated by Django 5.2.11 on 2026-08-17 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_menuitem_sizes_enabled_menusize'),
        ('users', '0011_remove_cartitem_unique_user_product_variant_cart_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='menu_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.menusize'),
        ),
    ]
