# Generated by Django 5.2.11 on 2026-08-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_cartitem_menu_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='pay_with_points',
            field=models.BooleanField(default=False),
        ),
    ]
