apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end}}
  init.sql: |
    CREATE DATABASE IF NOT EXIST {{.Values.config.MYSQL_DATABASE}};
