/**
 * Generates `src/core-elements/breakpoints.generated.css` from the
 * single-source-of-truth `BREAKPOINTS` scale in this package
 * (`src/core-elements/breakpoints.ts`). The output is a set of `@custom-media`
 * rules that `postcss-custom-media` (fed globally by
 * `@csstools/postcss-global-data`) resolves at build time - so any CSS file,
 * both inside `@repo/ui` and in every consumer app, can write
 * `@media (--below-sm) { ... }` instead of hardcoding `599.98px`.
 *
 * This is the ONE home of the generated tokens. Each consumer app's
 * `postcss.config.mjs` points `@csstools/postcss-global-data` at this file
 * (`../../packages/ui/src/core-elements/breakpoints.generated.css`), so the
 * scale is defined once and injected into every app's CSS pipeline.
 *
 * Run: `pnpm --filter @repo/ui gen:breakpoints` (each app's `predev`/`prebuild`
 * delegates here via its own `gen:breakpoints` alias).
 *
 * The generated file is committed so a clean checkout builds without the codegen
 * having run yet; it is regenerated (and should be re-committed) whenever the
 * BREAKPOINTS scale changes. Never edit it by hand.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { BREAKPOINTS, type Breakpoint } from "../src/core-elements/breakpoints";

// Ordered small→large; xs is the 0-width base.
const ORDER: Breakpoint[] = ["xs", "sm", "md", "lg", "xl"];

// A media query's max-width sits 0.02px under the next breakpoint's min so the
// "below" and "from" bands never both match at the exact threshold pixel.
const EPSILON = 0.02;

function px(n: number): string {
  return `${n}px`;
}

function maxPx(n: number): string {
  return `${n - EPSILON}px`;
}

function build(): string {
  const lines: string[] = [
    "/**",
    " * GENERATED by scripts/gen-breakpoints-css.ts from @repo/ui BREAKPOINTS.",
    " * Do not edit by hand - run `pnpm --filter @repo/ui gen:breakpoints` to regenerate.",
    " *",
    " * Usage in any CSS file (in @repo/ui or any consumer app):",
    " *   @media (--below-sm) { ... }   below the sm breakpoint (mobile only)",
    " *   @media (--md)       { ... }   from the md breakpoint up",
    " *   @media (--only-lg)  { ... }   within the lg band only",
    " */",
    "",
  ];

  for (let i = 0; i < ORDER.length; i++) {
    const bp = ORDER[i]!;
    const min = BREAKPOINTS[bp];
    const next = ORDER[i + 1];
    const nextMin = next ? BREAKPOINTS[next] : undefined;

    lines.push(`/* ${bp} */`);

    // "--<bp>": from this breakpoint's min-width up. Skip xs (min 0 is always true).
    if (min > 0) {
      lines.push(`@custom-media --${bp} (min-width: ${px(min)});`);
    }

    // "--below-<bp>": under this breakpoint. Skip xs (nothing below 0).
    if (min > 0) {
      lines.push(`@custom-media --below-${bp} (max-width: ${maxPx(min)});`);
    }

    // "--only-<bp>": within this breakpoint's own band.
    if (min === 0 && nextMin !== undefined) {
      lines.push(`@custom-media --only-${bp} (max-width: ${maxPx(nextMin)});`);
    } else if (nextMin !== undefined) {
      lines.push(
        `@custom-media --only-${bp} (min-width: ${px(min)}) and (max-width: ${maxPx(nextMin)});`,
      );
    } else {
      lines.push(`@custom-media --only-${bp} (min-width: ${px(min)});`);
    }

    lines.push("");
  }

  return lines.join("\n");
}

const outPath = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "core-elements",
  "breakpoints.generated.css",
);

writeFileSync(outPath, build(), "utf8");
console.log(`Wrote ${outPath}`);
