apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-api.fullname" . }}
  labels:
    {{- include "minecraft-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- if .Values.nginx.enabled }}
    - port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
      protocol: TCP
      name: nginx-http
    {{- end }}
  selector:
    {{- include "minecraft-api.selectorLabels" . | nindent 4 }}
