apiVersion: v1
kind: Service
metadata:
  name: {{ include "diarization.fullname" . }}-mongodb
  labels:
    {{- include "diarization.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
