apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "diarization.fullname" . }}-mongodb
  labels:
    {{- include "diarization.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.storage.size }}
  {{- if .Values.mongodb.storage.storageClass }}
  storageClassName: {{ .Values.mongodb.storage.storageClass }}
  {{- end }}
