# Generated by Django 4.1.9 on 2024-01-23 08:37

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, validators=[common.validators.ModelValidators.code]),
        ),
    ]
