replicaCount: 1
volumeMountPath: 'shared-volume'
nginxServiceName: 'nginx-web-app'
branch: 'main'

image:
  registry: registry_REPLACE
  repository: repository_REPLACE
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000

ingress:
  enabled: true
  host: host_REPLACE

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

deployment:
  nodeSelector:
    nodeProjects: node1
