# Generated by Django 5.2.11 on 2026-07-28 18:32

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('site_name', models.CharField(default='Field Journal', max_length=64)),
                ('site_description', models.TextField(blank=True, null=True)),
                ('en_site_description', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('social_links', models.JSONField(blank=True, default=list, help_text='Ordered social links, e.g. [{"platform": "instagram", "url": "https://instagram.com/acme"}]. A JSON list rather than a column per network, so adding or reordering platforms needs no migration.')),
                ('img_logo', models.ImageField(blank=True, null=True, upload_to=core.models.brand_image)),
                ('img_logo_hero', models.ImageField(blank=True, null=True, upload_to=core.models.brand_image)),
                ('img_favicon', models.ImageField(blank=True, null=True, upload_to=core.models.brand_image)),
                ('img_brandmark', models.ImageField(blank=True, null=True, upload_to=core.models.brand_image)),
                ('img_about', models.ImageField(blank=True, null=True, upload_to=core.models.brand_image)),
                ('img_hero', models.ImageField(blank=True, null=True, upload_to=core.models.brand_image)),
                ('img_manifest_1080', models.ImageField(blank=True, null=True, upload_to=core.models.brand_image)),
                ('img_manifest_512', models.ImageField(blank=True, null=True, upload_to=core.models.brand_image)),
                ('img_manifest_256', models.ImageField(blank=True, null=True, upload_to=core.models.brand_image)),
                ('img_manifest_192', models.ImageField(blank=True, null=True, upload_to=core.models.brand_image)),
                ('img_manifest_128', models.ImageField(blank=True, null=True, upload_to=core.models.brand_image)),
                ('primary_color', models.CharField(default='#06b6d4', max_length=16)),
                ('secondary_color', models.CharField(default='#7c9a3f', max_length=16)),
                ('google_font_url', models.URLField(blank=True, default='', help_text='Google Fonts stylesheet URL, e.g. https://fonts.googleapis.com/css2?family=Fraunces:wght@300..700&family=Karla:wght@400;700&display=swap. Blank keeps the default font.', max_length=512, validators=[core.models.validate_google_font_url])),
                ('font_display', models.CharField(blank=True, default='', help_text="CSS family name for headings, e.g. 'Fraunces'. Must be loaded by the URL above.", max_length=64)),
                ('font_body', models.CharField(blank=True, default='', help_text="CSS family name for body text, e.g. 'Karla'. Must be loaded by the URL above.", max_length=64)),
                ('hero_text_frame', models.BooleanField(default=False, help_text='Wrap page and section headings in an outline frame (with the brandmark badge if set).')),
                ('watermark_enabled', models.BooleanField(default=False, help_text='Tile the logo faintly behind every public page.')),
                ('watermark_rotation', models.SmallIntegerField(default=-12, help_text='Rotation of the tiled pattern in degrees (-45 to 45).')),
                ('watermark_intercalated', models.BooleanField(default=False, help_text="Alternate each tile's rotation so neighbours lean opposite ways.")),
                ('watermark_show_logo', models.BooleanField(default=True, help_text='Include the logo in the watermark.')),
                ('watermark_show_brandmark', models.BooleanField(default=False, help_text='Include the brandmark in the watermark (needs a brandmark image). With the logo also on, the two are intercalated.')),
                ('watermark_size', models.PositiveSmallIntegerField(default=120, help_text='Drawn width of one tile in px.')),
                ('watermark_spacing', models.PositiveSmallIntegerField(default=70, help_text='Empty space between tiles in px (added to the tile size).')),
                ('watermark_opacity', models.PositiveSmallIntegerField(default=4, help_text='Opacity of the pattern as a whole percent (1-25).')),
                ('background_light', models.CharField(default='#e5e5e5', help_text='Page background in the light theme.', max_length=16)),
                ('background_dark', models.CharField(default='#3c3c3c', help_text='Page background in the dark theme.', max_length=16)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to=core.models.backup_upload_path)),
                ('sections', models.JSONField(default=list)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('media_files', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Backup',
                'verbose_name_plural': 'Site Backups',
                'ordering': ['-created'],
            },
        ),
    ]
