# Generated by Django 5.2.11 on 2026-07-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='video_codec',
            field=models.CharField(choices=[('h264', 'H.264'), ('hevc', 'HEVC / H.265')], default='h264', help_text='H.264 plays everywhere. HEVC files are ~30%% smaller but need hardware decode support - Firefox and many desktop browsers will not play them at all.', max_length=8),
        ),
        migrations.AddField(
            model_name='system',
            name='video_max_height',
            field=models.PositiveSmallIntegerField(choices=[(720, '720p'), (1080, '1080p'), (1440, '1440p'), (2160, '2160p (4K)')], default=1080, help_text='Cap on the long edge of an uploaded clip. Never upscales: a smaller source is left at its own size.'),
        ),
        migrations.AddField(
            model_name='system',
            name='video_quality',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Maximum'), (23, 'High'), (26, 'Balanced'), (29, 'Small file')], default=23, help_text='Constant Rate Factor. Lower is better quality and a bigger file.'),
        ),
    ]
