# Generated by Django 5.2.11 on 2026-07-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_system_video_codec_system_video_max_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='video_max_height',
            field=models.PositiveSmallIntegerField(choices=[(720, '720p'), (1080, '1080p'), (1440, '1440p'), (2160, '2160p (4K)')], default=1080, help_text="Cap on the short edge of an uploaded clip - what '1080p' means, applied whichever way round the clip is. Never upscales: a smaller source is left at its own size."),
        ),
    ]
