# Generated by Django 5.2.11 on 2026-08-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_system_video_max_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='map_attribution',
            field=models.CharField(blank=True, default='', help_text="Only used when the style is 'Custom'. The credit drawn in the map's corner - required by every tile provider. Left blank, the OpenStreetMap credit is used.", max_length=200),
        ),
        migrations.AddField(
            model_name='system',
            name='map_style',
            field=models.CharField(choices=[('osm', 'OpenStreetMap standard'), ('carto-light', 'CARTO Positron (pale)'), ('carto-dark', 'CARTO Dark Matter'), ('carto-voyager', 'CARTO Voyager'), ('custom', 'Custom tile server')], default='osm', help_text="Which basemap the site's maps are drawn from. 'Custom' uses the tile URL below - a provider needing an API key, or a tile server of your own.", max_length=32),
        ),
        migrations.AddField(
            model_name='system',
            name='map_tile_url',
            field=models.CharField(blank=True, default='', help_text="Only used when the style is 'Custom'. A {z}/{x}/{y} template, e.g. https://tiles.example.com/styles/plain/{z}/{x}/{y}.png", max_length=500),
        ),
    ]
