# Generated by Django 5.2.11 on 2026-08-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_system_map_attribution_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='map_style',
            field=models.CharField(choices=[('osm', 'OpenStreetMap standard'), ('carto-light', 'CARTO Positron (pale)'), ('carto-dark', 'CARTO Dark Matter'), ('carto-voyager', 'CARTO Voyager'), ('custom', 'Custom tile server')], default='osm', help_text="Which basemap the site's maps are drawn from. 'Custom' uses the tile URL below - a provider needing an API key (MapTiler, Mapbox, Thunderforest), or a tile server of your own.", max_length=32),
        ),
        migrations.AlterField(
            model_name='system',
            name='map_tile_url',
            field=models.CharField(blank=True, default='', help_text="Only used when the style is 'Custom'. A {z}/{x}/{y} template, e.g. https://api.maptiler.com/maps/streets-v2/{z}/{x}/{y}.png?key=YOUR_KEY", max_length=500),
        ),
    ]
