# Generated by Django 4.1.9 on 2024-01-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_year_alter_vehiclemake_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicleclassification',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiclefeature',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiclemake',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiclepicture',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
