# Generated by Django 5.2.11 on 2026-07-28 06:56

import colorfield.fields
import core.fields
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('fit', models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('image', core.fields.ResizedImageField(blank=True, max_size=[1200, None], null=True, upload_to=core.models.picture)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('icon', core.fields.ResizedImageField(blank=True, max_size=[128, None], null=True, quality=90, upload_to=core.models.picture)),
                ('months', models.JSONField(blank=True, default=list, help_text="Month numbers this season covers, 1-12 (e.g. [9, 10, 11] for a northern-hemisphere autumn). Used to fill a sighting's season from its date.")),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('fit', models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('image', core.fields.ResizedImageField(blank=True, max_size=[1200, None], null=True, upload_to=core.models.picture)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('icon', core.fields.ResizedImageField(blank=True, max_size=[128, None], null=True, quality=90, upload_to=core.models.picture)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Weather Condition',
                'verbose_name_plural': 'Weather Conditions',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('fit', models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('image', core.fields.ResizedImageField(blank=True, max_size=[1200, None], null=True, upload_to=core.models.picture)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('animal', 'Animals'), ('plant', 'Plants'), ('fungus', 'Fungi'), ('season', 'Seasons'), ('weather', 'Weather')], help_text='Which of the five top-level branches this category belongs to. Everything filed under it inherits this branch.', max_length=16)),
                ('icon', core.fields.ResizedImageField(blank=True, max_size=[128, None], null=True, quality=90, upload_to=core.models.picture)),
                ('scientific_name', models.CharField(blank=True, help_text='Taxonomic group this category corresponds to, if any (e.g. "Cervidae" for Deer). Free text - not validated.', max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Surface this category on the landing page.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['kind', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['kind', 'sort_order'], name='catalog_cat_kind_098c54_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('place_type', models.CharField(blank=True, choices=[('park', 'Park'), ('reserve', 'Nature Reserve'), ('forest', 'Forest'), ('trail', 'Trail'), ('garden', 'Garden'), ('lake', 'Lake'), ('river', 'River'), ('beach', 'Beach'), ('wetland', 'Wetland'), ('mountain', 'Mountain'), ('desert', 'Desert'), ('urban', 'Urban'), ('backyard', 'Backyard'), ('other', 'Other')], default='other', max_length=16, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('region', models.CharField(blank=True, help_text='State, province or region.', max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('map_link', models.URLField(blank=True, help_text='Google Maps / OpenStreetMap link to the place.', max_length=500, null=True)),
                ('hide_precise_location', models.BooleanField(default=False, help_text='Round published coordinates to ~1 km for this place and every sighting at it. Use for nesting sites and sensitive species.')),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('fit', models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('image', core.fields.ResizedImageField(blank=True, max_size=[1200, None], null=True, upload_to=core.models.picture)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('icon', core.fields.ResizedImageField(blank=True, max_size=[128, None], null=True, quality=90, upload_to=core.models.picture)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('family', models.CharField(blank=True, max_length=255, null=True)),
                ('video_link', models.URLField(blank=True, help_text='YouTube, Vimeo or direct video URL rendered as a hero above the detail page.', max_length=500, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(help_text='The sub-category this belongs to. Its `kind` is what places this entry in one of the five branches.', on_delete=django.db.models.deletion.PROTECT, related_name='species', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpeciesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('fit', models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('image', core.fields.ResizedImageField(blank=True, max_size=[1200, None], null=True, upload_to=core.models.picture)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.species')),
            ],
            options={
                'verbose_name': 'Species Image',
                'verbose_name_plural': 'Species Images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['category', 'sort_order'], name='catalog_spe_categor_81545e_idx'),
        ),
    ]
