# Generated by Django 5.2.11 on 2026-07-29 16:17

import core.fields
import core.models
from django.db import migrations


class Migration(migrations.Migration):
    """Behaviour only: the ICON tier went 128 -> 192 px.

    ``ResizedImageField.deconstruct()`` records ``max_size``, so bumping the
    constant in ``core.image_sizes`` shows up as an AlterField on every icon
    column. ``max_size`` is resize behaviour applied in ``pre_save``, not a
    column type - the column stays ``varchar(100)`` and no value changes. On
    Postgres that makes this a no-op; on SQLite (development and the tests)
    Django still rebuilds each table, because it rebuilds for *any* AlterField.

    It also re-processes **nothing**. Icons already on disk stay at the 128 px
    they were written at; only the next upload of one gets the new bound. The
    originals are gone, so the only way to sharpen an existing glyph is to
    re-upload it from its source file.
    """

    dependencies = [
        ('catalog', '0006_state_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=core.fields.ResizedImageField(blank=True, max_size=[192, None], null=True, quality=90, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='location',
            name='icon',
            field=core.fields.ResizedImageField(blank=True, max_size=[192, None], null=True, quality=90, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='season',
            name='icon',
            field=core.fields.ResizedImageField(blank=True, max_size=[192, None], null=True, quality=90, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='species',
            name='icon',
            field=core.fields.ResizedImageField(blank=True, max_size=[192, None], null=True, quality=90, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='weathercondition',
            name='icon',
            field=core.fields.ResizedImageField(blank=True, max_size=[192, None], null=True, quality=90, upload_to=core.models.picture),
        ),
    ]
