# Generated by Django 5.2.11 on 2026-07-29 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_category_icon_alter_location_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The account that proposed this entry, for entries filed through the public contribute flow. Never published.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_species', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='species',
            name='is_contribution',
            field=models.BooleanField(default=False, help_text='Proposed through the public contribute flow rather than the CMS. Such an entry starts disabled and joins the catalog when an administrator enables it.'),
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['created_by'], name='catalog_spe_created_e7616d_idx'),
        ),
    ]
