# Generated by Django 5.2.11 on 2026-07-31 22:21

import core.fields
import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=core.fields.ResizedImageField(blank=True, help_text="The place's main image. Leave empty to use the first photo below.", max_size=[1200, None], null=True, upload_to=core.models.picture),
        ),
    ]
