# Generated by Django 5.2.11 on 2026-08-01 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_drop_main_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The account that proposed this place, for places filed through the public contribute flow. Never published.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='is_contribution',
            field=models.BooleanField(default=False, help_text='Proposed through the public contribute flow rather than the CMS. Such a place starts disabled and joins the catalog when an administrator enables it.'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['created_by'], name='catalog_loc_created_fbb2d8_idx'),
        ),
    ]
