# Generated by Django 5.2.11 on 2026-08-06 23:06
#
# `was_published` latches the first time a row is saved live, so every row that
# is **already** live when this runs has to be backfilled - otherwise the whole
# published catalog reads as "never reviewed" to the contributor's own list, and
# a species that has been on the site for a year would be badged as awaiting its
# first approval.
#
# The backfill is `enabled=True` alone, deliberately: it is the only evidence the
# database holds that an administrator ever published a row, and it is exactly
# what the flag means going forward. A row disabled *before* this migration ran
# is indistinguishable from one that was never published, and is left False -
# the honest answer, since nothing recorded otherwise.

from django.db import migrations, models


def backfill(apps, schema_editor):
    for label in ('Location', 'Species'):
        model = apps.get_model('catalog', label)
        model.objects.filter(enabled=True).update(was_published=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_location_created_by_location_is_contribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='was_published',
            field=models.BooleanField(default=False, help_text='Whether an administrator has ever published this row. Set the first time it is saved enabled and never cleared, so a contribution awaiting its first review can be told apart from a published one its author has edited back into review.'),
        ),
        migrations.AddField(
            model_name='species',
            name='was_published',
            field=models.BooleanField(default=False, help_text='Whether an administrator has ever published this row. Set the first time it is saved enabled and never cleared, so a contribution awaiting its first review can be told apart from a published one its author has edited back into review.'),
        ),
        # Reversing only drops the column, so the backfill has nothing to undo.
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
