# Generated by Django 5.2.11 on 2026-07-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passkeycredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Can edit the site through the Next.js CMS and the write API. Django staff already have this implicitly.'),
        ),
    ]
