# Generated by Django 4.1.9 on 2023-07-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userpicture_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPicture',
        ),
    ]
