# Generated by Django 5.2.11 on 2026-06-15 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(choices=[('adzuna', 'Adzuna'), ('jsearch', 'JSearch')], max_length=20)),
                ('provider_uid', models.CharField(max_length=255)),
                ('dedup_hash', models.CharField(db_index=True, max_length=40)),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True)),
                ('job_url', models.URLField(max_length=2048)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('CAD', 'CAD'), ('EUR', 'EUR'), ('MXN', 'MXN'), ('GBP', 'GBP')], max_length=3)),
                ('work_type', models.JSONField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, choices=[('us', 'United States'), ('ca', 'Canada'), ('mx', 'Mexico')], db_index=True, max_length=2)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['country', '-created'], name='jobs_jobpos_country_57ff7a_idx'), models.Index(fields=['is_private', 'owner'], name='jobs_jobpos_is_priv_a358e2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('provider', 'provider_uid'), name='unique_shared_posting'), models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('provider', 'provider_uid', 'owner'), name='unique_private_posting')],
            },
        ),
        migrations.CreateModel(
            name='UserApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(choices=[('adzuna', 'Adzuna'), ('jsearch', 'JSearch')], max_length=20)),
                ('encrypted_key', models.TextField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider'],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='unique_credential_per_user_provider')],
            },
        ),
    ]
