# Generated by Django 5.2.11 on 2026-06-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapicredential',
            name='call_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userapicredential',
            name='calls_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userapicredential',
            name='usage_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
