# Generated by Django 5.2.11 on 2026-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_nafta_tn_likelihood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearch',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
