# Generated by Django 5.2.11 on 2026-06-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobsearch_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='language_requirement_unmet',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
