# Generated by Django 5.2.11 on 2026-06-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobposting_language_requirement_unmet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapicredential',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userapicredential',
            name='encrypted_key',
            field=models.TextField(blank=True),
        ),
    ]
