# Generated by Django 4.1.9 on 2023-06-28 22:08

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_changelog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NediiPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=32, unique=True, validators=[common.validators.ModelValidators.name])),
                ('unlimited_items', models.BooleanField(default=False, verbose_name='Anuncios ilimitados?')),
                ('number_of_items', models.PositiveSmallIntegerField(blank=True, default=4, null=True, verbose_name='Numero de anuncios')),
                ('advertising_days', models.PositiveSmallIntegerField(blank=True, default=5, null=True, verbose_name='Numero de dias de publicidad')),
                ('stand_enabled', models.BooleanField(default=True, verbose_name='Stand habilitado?')),
                ('digital_card', models.BooleanField(default=True, verbose_name='Terjeta digital habilitada?')),
                ('billed_monthly', models.BooleanField(default=True, verbose_name='Cobrado mensualmente?')),
                ('exposure', models.CharField(blank=True, choices=[('basic', 'basic'), ('medium', 'medium'), ('high', 'high'), ('full', 'full')], max_length=8, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Precio del plan', max_digits=10, verbose_name='Precio del plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
