"""
Django settings for website_api project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Local development reads .env; in Docker/Helm the same names arrive as real
# environment variables, which load_dotenv leaves untouched (it never overrides).
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# Trust the X-Forwarded-Proto header set by the reverse proxy (ingress/nginx)
# so Django knows requests are HTTPS even though it receives them over HTTP internally.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'https://website-api.iguzman.com.mx,https://website.iguzman.com.mx',
    ).split(',')
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'colorfield',
    'core',
    'users',
    'catalog',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'website_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'website_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Uses PostgreSQL when DB_HOST is set (production/staging).
# Falls back to SQLite for local development.

_DB_HOST = os.environ.get('DB_HOST', '')

if _DB_HOST:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'website'),
            'USER': os.environ.get('DB_USER', 'website'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': _DB_HOST,
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ── Media files (uploaded by users) ──────────────────────────────────────────
# One switch, `R2_ACCOUNT_ID`, decides the whole media stack:
#
#   set   -> production. Every upload goes to Cloudflare R2 and is served from
#            the CDN; `core.storage.TenantMediaStorage` picks the bucket per
#            tenant (a customer on its own domain can connect its own R2 in the
#            CMS - see core/storage.py).
#   unset -> development. Files land in `media/` exactly as they always have,
#            with no Cloudflare account, no credentials and no network calls.
#
# Static files stay on whitenoise either way: they ship inside the image, are
# already hashed and compressed at build time, and are served by the same process
# that renders the Django admin - putting them behind a bucket would add a
# round-trip and a failure mode for no gain.
R2_ACCOUNT_ID = os.environ.get('R2_ACCOUNT_ID', '')
R2_ACCESS_KEY_ID = os.environ.get('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY', '')
R2_BUCKET_NAME = os.environ.get('R2_BUCKET_NAME', '')
R2_PUBLIC_DOMAIN = os.environ.get('R2_PUBLIC_DOMAIN', '').strip().rstrip('/')

# Hosts under this suffix are *our* sites and belong on the platform bucket
# above; anything else is a customer on its own domain, which is expected to
# connect its own R2 account in the CMS. `SystemMediaMigrationView` reads this to
# decide which bucket a tenant's media migration targets, and therefore which
# configuration has to be present before the CMS will let it run.
PLATFORM_HOST_SUFFIX = os.environ.get('PLATFORM_HOST_SUFFIX', '.iguzman.com.mx').strip().lower()

if R2_ACCOUNT_ID:
    STORAGES = {
        'default': {
            'BACKEND': 'core.storage.TenantMediaStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }
    # The platform bucket's public hostname. `FileField.url` returns an absolute
    # URL from here on, which is what lets the frontend fetch straight from the
    # edge - see `core.media.absolute_media_url` for the callers that used to
    # assume a relative one.
    MEDIA_URL = f'https://{R2_PUBLIC_DOMAIN}/' if R2_PUBLIC_DOMAIN else '/media/'
    # Still read by `sync_media_to_r2` as the source to copy *from*, and by any
    # local tooling; nothing writes here once R2 is on.
    MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media')))
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }
    MEDIA_URL = '/media/'
    MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media')))

# Origin for media URLs that are *relative* - i.e. the local-filesystem branch
# above - in contexts with no request to resolve them against (e.g. branded
# emails, whose tenant logo must load inside an email client). On R2 the storage
# backend already returns absolute URLs and this is not consulted; always go
# through `core.media.absolute_media_url`, never concatenate it yourself, or an
# R2 URL comes out as `https://website-api…https://cdn…`.
MEDIA_BASE_URL = os.environ.get('MEDIA_BASE_URL', 'https://website-api.iguzman.com.mx').rstrip('/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

# Cache
# https://github.com/jazzband/django-redis
#
# Uses Redis when REDIS_URL is set (production/staging).
# Falls back to the local-memory cache for local development.

_REDIS_URL = os.environ.get('REDIS_URL', '')

if _REDIS_URL:
    _redis_options: dict = {
        'CLIENT_CLASS': 'django_redis.client.DefaultClient',
    }
    _redis_password = os.environ.get('REDIS_PASSWORD', '')
    if _redis_password:
        _redis_options['PASSWORD'] = _redis_password

    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': _REDIS_URL,
            'OPTIONS': _redis_options,
        }
    }

    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'

# Email
# https://docs.djangoproject.com/en/5.2/topics/email/
#
# Uses SMTP via IONOS when EMAIL_HOST_USER is set.
# Falls back to the console backend for local development.

_EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')

if _EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.ionos.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = _EMAIL_HOST_USER
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@localhost'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://website.iguzman.com.mx/')
EMAIL_VERIFICATION_TOKEN_EXPIRY_HOURS = int(os.environ.get('EMAIL_VERIFICATION_TOKEN_EXPIRY_HOURS', '24'))

# CORS
# https://github.com/adamchainz/django-cors-headers
#
# In production, set CORS_ALLOWED_ORIGINS via env var instead of using CORS_ALLOW_ALL_ORIGINS.

_CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '')

if _CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _CORS_ALLOWED_ORIGINS.split(',') if o.strip()]
else:
    CORS_ALLOW_ALL_ORIGINS = DEBUG

# LLM providers
#
# All AI calls go through core/services/llm.py: Groq is primary, OpenRouter is the
# fallback for any Groq failure. Mirrors cinelog-api's configuration.

GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
GROQ_MODEL = os.environ.get('GROQ_MODEL', 'openai/gpt-oss-120b')

OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY', '')
OPENROUTER_MODEL = os.environ.get('OPENROUTER_MODEL', 'meta-llama/llama-3.3-70b-instruct')

LLM_REQUEST_TIMEOUT = float(os.environ.get('LLM_REQUEST_TIMEOUT', '20'))

# Scraper microservice
#
# The web search / page-extraction service (https://scraper.iguzman.com.mx) that
# the ingredient "Search on web" nutrition lookup uses. Shared with cinelog-api.
SCRAPER_BASE_URL = os.environ.get('SCRAPER_BASE_URL', 'https://scraper.iguzman.com.mx')
SCRAPER_API_KEY = os.environ.get('SCRAPER_API_KEY', '')

# Stripe
# ------
# There is deliberately no STRIPE_SECRET_KEY here: this is a multi-tenant API and
# every System holds its own Stripe account's keys, encrypted at rest (see
# core.crypto and core.models.System). The only global knob is the key those
# ciphertexts are encrypted with.
#
# When unset, core.crypto derives one from SECRET_KEY. Set a dedicated key in any
# environment where SECRET_KEY may rotate - rotating it would orphan every stored
# Stripe credential and silently break checkout for every tenant.
STRIPE_CREDENTIALS_ENCRYPTION_KEY = os.environ.get('STRIPE_CREDENTIALS_ENCRYPTION_KEY', '')

# How long a Checkout Session stays payable (seconds). Stripe's own floor is 30
# minutes; a pending Order whose session lapses is left for the customer to
# re-checkout rather than being resurrected.
STRIPE_CHECKOUT_SESSION_TTL = int(os.environ.get('STRIPE_CHECKOUT_SESSION_TTL', 30 * 60))
