"""
Django settings for website_api project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Local development reads .env; in Docker/Helm the same names arrive as real
# environment variables, which load_dotenv leaves untouched (it never overrides).
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# Trust the X-Forwarded-Proto header set by the reverse proxy (ingress/nginx)
# so Django knows requests are HTTPS even though it receives them over HTTP internally.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'https://website-api.iguzman.com.mx,https://website.iguzman.com.mx',
    ).split(',')
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'colorfield',
    'core',
    'users',
    'catalog',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'website_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'website_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Uses PostgreSQL when DB_HOST is set (production/staging).
# Falls back to SQLite for local development.

_DB_HOST = os.environ.get('DB_HOST', '')

if _DB_HOST:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'website'),
            'USER': os.environ.get('DB_USER', 'website'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': _DB_HOST,
            'PORT': os.environ.get('DB_PORT', '5432'),
            # Reuse a connection for a minute instead of opening a new one per
            # request. At the request rates the CMS produces while an operator is
            # editing, per-request connects are pure overhead - and each one is a
            # chance to block on a database that is busy accepting.
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
            # Django 4.1+: check a pooled connection is still usable before handing
            # it to a view, so a connection dropped between requests surfaces as a
            # retry rather than an error in the middle of a write.
            'CONN_HEALTH_CHECKS': True,
            'OPTIONS': {
                # Never wait indefinitely on the TCP connect. Without this a
                # database that stops accepting connections hangs every worker
                # thread until gunicorn's 600s timeout.
                'connect_timeout': int(os.environ.get('DB_CONNECT_TIMEOUT', '5')),
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ── Media files (uploaded by users) ──────────────────────────────────────────
# **Production stores media in Cloudflare R2, and only there.** Every upload goes
# to a bucket and is served from the CDN; `core.storage.TenantMediaStorage` picks
# the bucket per tenant (a customer on its own domain can connect its own R2 in
# the CMS - see core/storage.py). The hostPath volume that used to hold media on
# a cluster node is gone, along with the nginx sidecar that served it: a node
# failure took the files with it, and nothing rebuilt them.
#
# `R2_ACCOUNT_ID` unset is now a **development-only** mode: files land in
# `media/` on local disk so `manage.py runserver` and the test suite need no
# Cloudflare account, no credentials and no network calls. It is not a production
# fallback - a pod is ephemeral and its disk is not backed up, so an unset
# `R2_ACCOUNT_ID` in the cluster means uploads are silently thrown away on the
# next rollout. The chart therefore does not define it; it comes from the Secret.
#
# Static files stay on whitenoise either way: they ship inside the image, are
# already hashed and compressed at build time, and are served by the same process
# that renders the Django admin - putting them behind a bucket would add a
# round-trip and a failure mode for no gain.
R2_ACCOUNT_ID = os.environ.get('R2_ACCOUNT_ID', '')
R2_ACCESS_KEY_ID = os.environ.get('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY', '')
R2_BUCKET_NAME = os.environ.get('R2_BUCKET_NAME', '')
R2_PUBLIC_DOMAIN = os.environ.get('R2_PUBLIC_DOMAIN', '').strip().rstrip('/')

if R2_ACCOUNT_ID:
    STORAGES = {
        'default': {
            'BACKEND': 'core.storage.TenantMediaStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }
    # The platform bucket's public hostname. `FileField.url` returns an absolute
    # URL from here on, which is what lets the frontend fetch straight from the
    # edge - see `core.media.absolute_media_url` for the callers that used to
    # assume a relative one.
    MEDIA_URL = f'https://{R2_PUBLIC_DOMAIN}/' if R2_PUBLIC_DOMAIN else '/media/'
    # Nothing reads or writes here with R2 on; kept defined only because Django
    # and third-party code (ImageField validation, test helpers) expect the
    # setting to exist.
    MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media')))
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }
    MEDIA_URL = '/media/'
    MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media')))

# Origin for media URLs that are *relative* - i.e. the development-only
# local-filesystem branch above - in contexts with no request to resolve them
# against (e.g. branded emails, whose tenant logo must load inside an email
# client). In production the storage backend already returns absolute URLs and
# this is never consulted; always go
# through `core.media.absolute_media_url`, never concatenate it yourself, or an
# R2 URL comes out as `https://website-api…https://cdn…`.
MEDIA_BASE_URL = os.environ.get('MEDIA_BASE_URL', 'https://website-api.iguzman.com.mx').rstrip('/')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

# Cache
# https://github.com/jazzband/django-redis
#
# Uses Redis when REDIS_URL is set (production/staging).
# Falls back to the local-memory cache for local development.

_REDIS_URL = os.environ.get('REDIS_URL', '')

if _REDIS_URL:
    _redis_options: dict = {
        'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        # ⚠ redis-py defaults BOTH of these to None, which means a blocking read
        # with no deadline. Sessions live in this cache (SESSION_ENGINE below), so
        # without a timeout a Redis that accepts the socket but stops answering
        # hangs every worker thread that touches a session - including the health
        # probe, which is how a cache blip used to get the whole pod restarted.
        'SOCKET_CONNECT_TIMEOUT': int(os.environ.get('REDIS_CONNECT_TIMEOUT', '3')),
        'SOCKET_TIMEOUT': int(os.environ.get('REDIS_SOCKET_TIMEOUT', '3')),
        # Reconnect instead of surfacing a stale pooled socket after an idle gap.
        'RETRY_ON_TIMEOUT': True,
        'CONNECTION_POOL_KWARGS': {
            'health_check_interval': 30,
        },
        # The cache is an accelerator here, never the source of truth: every cached
        # payload is rebuilt from Postgres on a miss. Treating a Redis outage as a
        # miss keeps the site serving (slower) instead of 500ing every request.
        'IGNORE_EXCEPTIONS': True,
    }
    _redis_password = os.environ.get('REDIS_PASSWORD', '')
    if _redis_password:
        _redis_options['PASSWORD'] = _redis_password

    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': _REDIS_URL,
            'OPTIONS': _redis_options,
        }
    }

    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'default'

# Email
# https://docs.djangoproject.com/en/5.2/topics/email/
#
# Uses SMTP via IONOS when EMAIL_HOST_USER is set.
# Falls back to the console backend for local development.

_EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')

if _EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.ionos.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = _EMAIL_HOST_USER
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
    # ⚠ Django passes this straight to smtplib, and its default is None - i.e. a
    # socket with no deadline. Registration sends its verification mail
    # synchronously inside the request (users/views.py), so an SMTP host that
    # accepts the connection and then stalls would pin a worker thread until
    # gunicorn's 600s timeout. Bound it well under the probe budget instead.
    EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@localhost'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://website.iguzman.com.mx/')
EMAIL_VERIFICATION_TOKEN_EXPIRY_HOURS = int(os.environ.get('EMAIL_VERIFICATION_TOKEN_EXPIRY_HOURS', '24'))

# CORS
# https://github.com/adamchainz/django-cors-headers
#
# In production, set CORS_ALLOWED_ORIGINS via env var instead of using CORS_ALLOW_ALL_ORIGINS.

_CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '')

if _CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _CORS_ALLOWED_ORIGINS.split(',') if o.strip()]
else:
    CORS_ALLOW_ALL_ORIGINS = DEBUG

# LLM providers
#
# All AI calls go through core/services/llm.py: Groq is primary, OpenRouter is the
# fallback for any Groq failure. Mirrors cinelog-api's configuration.

GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
GROQ_MODEL = os.environ.get('GROQ_MODEL', 'openai/gpt-oss-120b')

OPENROUTER_API_KEY = os.environ.get('OPENROUTER_API_KEY', '')
OPENROUTER_MODEL = os.environ.get('OPENROUTER_MODEL', 'meta-llama/llama-3.3-70b-instruct')

LLM_REQUEST_TIMEOUT = float(os.environ.get('LLM_REQUEST_TIMEOUT', '20'))

# Scraper microservice
#
# The web search / page-extraction service (https://scraper.iguzman.com.mx) that
# the ingredient "Search on web" nutrition lookup uses. Shared with cinelog-api.
SCRAPER_BASE_URL = os.environ.get('SCRAPER_BASE_URL', 'https://scraper.iguzman.com.mx')
SCRAPER_API_KEY = os.environ.get('SCRAPER_API_KEY', '')

# Stock image banks
# -----------------
# Read by `core.services.image_banks`, whose only caller is the
# `fetch_seed_images` management command - the seeding step that fills a new
# customer's brief with real photography. Nothing in the request path touches
# these, so they belong in a developer's `.env` and are deliberately NOT in the
# cluster's `website-api-secrets`: seeding happens locally, and a key present in
# production would only invite someone to wire a bank search into a view.
PEXELS_API_KEY = os.environ.get('PEXELS_API_KEY', '')
PIXABAY_API_KEY = os.environ.get('PIXABAY_API_KEY', '')

# Stripe
# ------
# There is deliberately no STRIPE_SECRET_KEY here: this is a multi-tenant API and
# every System holds its own Stripe account's keys, encrypted at rest (see
# core.crypto and core.models.System). The only global knob is the key those
# ciphertexts are encrypted with.
#
# When unset, core.crypto derives one from SECRET_KEY. Set a dedicated key in any
# environment where SECRET_KEY may rotate - rotating it would orphan every stored
# Stripe credential and silently break checkout for every tenant.
STRIPE_CREDENTIALS_ENCRYPTION_KEY = os.environ.get('STRIPE_CREDENTIALS_ENCRYPTION_KEY', '')

# How long a Checkout Session stays payable (seconds). Stripe's own floor is 30
# minutes; a pending Order whose session lapses is left for the customer to
# re-checkout rather than being resurrected.
STRIPE_CHECKOUT_SESSION_TTL = int(os.environ.get('STRIPE_CHECKOUT_SESSION_TTL', 30 * 60))
