# Generated by Django 5.2.11 on 2026-07-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0002_bulletpoint_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletpoint',
            name='text',
            field=models.CharField(max_length=900),
        ),
    ]
