# Generated by Django 5.2.11 on 2026-06-08 04:10

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('barcode', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, choices=[('dvd', 'DVD'), ('bluray', 'Blu-ray'), ('4k', '4K UHD'), ('other', 'Other')], max_length=10)),
                ('cover_url', models.URLField(blank=True, max_length=1000)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=catalog.models._movie_cover_path)),
                ('tmdb_id', models.CharField(blank=True, max_length=20)),
                ('cast', models.ManyToManyField(blank=True, related_name='movies', to='catalog.actor')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='catalog.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ScanQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('barcode', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('review', 'Awaiting Review'), ('accepted', 'Accepted'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('raw_scraped_text', models.TextField(blank=True)),
                ('extracted_title', models.CharField(blank=True, max_length=500)),
                ('extracted_director', models.CharField(blank=True, max_length=255)),
                ('extracted_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extracted_cast', models.JSONField(blank=True, default=list)),
                ('extracted_cover_url', models.URLField(blank=True, max_length=1000)),
                ('extracted_cover_image', models.ImageField(blank=True, null=True, upload_to=catalog.models._scan_cover_path)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('movie', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_queue_entry', to='catalog.movie')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
