# Generated by Django 5.2.11 on 2026-06-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanqueue',
            name='extracted_genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scanqueue',
            name='extracted_tmdb_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
