# Generated by Django 5.2.11 on 2026-06-22 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_movie_synopsis_movie_trailer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=1000)),
                ('overview', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='catalog.scanqueue')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
