# Generated by Django 5.2.11 on 2026-06-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_scancandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanqueue',
            name='extracted_synopsis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanqueue',
            name='extracted_trailer_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
