# Generated by Django 5.2.11 on 2026-06-22 23:34

from django.db import migrations, models


def purge_accepted_entries(apps, schema_editor):
    """
    Accepted entries used to linger as tombstones linked to the promoted Movie.
    Accept now deletes the entry outright, so these rows are inert leftovers -
    remove them. Their candidates cascade away with them.
    """
    ScanQueue = apps.get_model('catalog', 'ScanQueue')
    ScanQueue.objects.filter(status='accepted').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_scanqueue_extracted_synopsis_and_more'),
    ]

    operations = [
        migrations.RunPython(purge_accepted_entries, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='scanqueue',
            name='movie',
        ),
        migrations.AlterField(
            model_name='scanqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('review', 'Awaiting Review'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
