# Generated by Django 5.2.11 on 2026-06-23 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Seed set for the Format lookup table (mirrors FORMAT_CHOICES in models.py).
FORMAT_SEED = [
    ('dvd', 'DVD'),
    ('bluray', 'Blu-ray'),
    ('4k', '4K UHD'),
    ('other', 'Other'),
]


def seed_formats_and_migrate_movies(apps, schema_editor):
    """
    Seed the Format table, then move each Movie's legacy single `barcode` and
    `format` onto the new decoupled models: a Barcode row per movie and the
    matching Format added to its `formats` M2M. Ownership is intentionally NOT
    backfilled - existing movies stay owner-less (read-only) until an owner is
    assigned by hand in the Django admin.
    """
    Format = apps.get_model('catalog', 'Format')
    Movie = apps.get_model('catalog', 'Movie')
    Barcode = apps.get_model('catalog', 'Barcode')

    code_to_format = {}
    for code, label in FORMAT_SEED:
        fmt, _ = Format.objects.get_or_create(code=code, defaults={'label': label})
        code_to_format[code] = fmt

    for movie in Movie.objects.all():
        fmt = code_to_format.get(movie.format) if movie.format else None
        if movie.barcode:
            Barcode.objects.get_or_create(
                code=movie.barcode, defaults={'movie': movie, 'format': fmt}
            )
        if fmt:
            movie.formats.add(fmt)


def reverse_noop(apps, schema_editor):
    # Forward-only data move; reversing the schema (re-adding the columns)
    # leaves them blank, which is acceptable for a rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_drop_scanqueue_movie_purge_accepted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('dvd', 'DVD'), ('bluray', 'Blu-ray'), ('4k', '4K UHD'), ('other', 'Other')], max_length=10, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='scanqueue',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_queue_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanqueue',
            name='barcode',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='catalog.movie')),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcodes', to='catalog.format')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='formats',
            field=models.ManyToManyField(blank=True, related_name='movies', to='catalog.format'),
        ),
        migrations.CreateModel(
            name='MovieOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownerships', to='catalog.barcode')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='catalog.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_ownerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('user', 'movie')},
            },
        ),
        # Move legacy barcode/format data onto the new models BEFORE dropping the
        # old columns (the historical Movie still has them at this point).
        migrations.RunPython(seed_formats_and_migrate_movies, reverse_noop),
        migrations.RemoveField(
            model_name='movie',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='format',
        ),
    ]
