# Generated by Django 5.2.11 on 2026-06-24 04:09

from django.db import migrations, models

from catalog.vocab import (
    AUDIO_FORMAT_CHOICES,
    HDR_FORMAT_CHOICES,
    LANGUAGE_CHOICES,
)


def seed_tech_spec_vocab(apps, schema_editor):
    """
    Seed the controlled-vocabulary lookup tables from ``catalog.vocab``.

    Idempotent (``get_or_create`` on the unique code) so a re-run never
    duplicates a row. Mirrors the Format seeding in 0008.
    """
    AudioFormat = apps.get_model('catalog', 'AudioFormat')
    HdrFormat = apps.get_model('catalog', 'HdrFormat')
    SpokenLanguage = apps.get_model('catalog', 'SpokenLanguage')
    SubtitleLanguage = apps.get_model('catalog', 'SubtitleLanguage')

    for code, label in AUDIO_FORMAT_CHOICES:
        AudioFormat.objects.get_or_create(code=code, defaults={'label': label})
    for code, label in HDR_FORMAT_CHOICES:
        HdrFormat.objects.get_or_create(code=code, defaults={'label': label})
    for code, name in LANGUAGE_CHOICES:
        SpokenLanguage.objects.get_or_create(code=code, defaults={'name': name})
        SubtitleLanguage.objects.get_or_create(code=code, defaults={'name': name})


def reverse_noop(apps, schema_editor):
    # The tables are dropped wholesale when the CreateModel ops reverse, so the
    # seeded rows go with them - nothing to undo here.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_format_remove_movie_barcode_remove_movie_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('atmos', 'Dolby Atmos'), ('truehd', 'Dolby TrueHD'), ('ddplus', 'Dolby Digital Plus'), ('dd', 'Dolby Digital'), ('dtsx', 'DTS:X'), ('dtshd', 'DTS-HD Master Audio'), ('dts', 'DTS'), ('lpcm', 'LPCM'), ('other', 'Other')], max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HdrFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('dolbyvision', 'Dolby Vision'), ('hdr10plus', 'HDR10+'), ('hdr10', 'HDR10'), ('hlg', 'HLG'), ('sdr', 'SDR')], max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese'), ('ru', 'Russian'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('nl', 'Dutch'), ('sv', 'Swedish'), ('da', 'Danish'), ('no', 'Norwegian'), ('fi', 'Finnish'), ('pl', 'Polish'), ('cs', 'Czech'), ('hu', 'Hungarian'), ('tr', 'Turkish'), ('th', 'Thai'), ('el', 'Greek'), ('he', 'Hebrew'), ('id', 'Indonesian'), ('uk', 'Ukrainian'), ('ro', 'Romanian'), ('vi', 'Vietnamese'), ('tl', 'Tagalog'), ('ca', 'Catalan')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubtitleLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese'), ('ru', 'Russian'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('nl', 'Dutch'), ('sv', 'Swedish'), ('da', 'Danish'), ('no', 'Norwegian'), ('fi', 'Finnish'), ('pl', 'Polish'), ('cs', 'Czech'), ('hu', 'Hungarian'), ('tr', 'Turkish'), ('th', 'Thai'), ('el', 'Greek'), ('he', 'Hebrew'), ('id', 'Indonesian'), ('uk', 'Ukrainian'), ('ro', 'Romanian'), ('vi', 'Vietnamese'), ('tl', 'Tagalog'), ('ca', 'Catalan')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scanqueue',
            name='extracted_audio_formats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scanqueue',
            name='extracted_hdr_formats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scanqueue',
            name='extracted_spoken_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scanqueue',
            name='extracted_subtitle_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='audio_formats',
            field=models.ManyToManyField(blank=True, related_name='movies', to='catalog.audioformat'),
        ),
        migrations.AddField(
            model_name='movie',
            name='hdr_formats',
            field=models.ManyToManyField(blank=True, related_name='movies', to='catalog.hdrformat'),
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_languages',
            field=models.ManyToManyField(blank=True, related_name='movies', to='catalog.spokenlanguage'),
        ),
        migrations.AddField(
            model_name='movie',
            name='subtitle_languages',
            field=models.ManyToManyField(blank=True, related_name='movies', to='catalog.subtitlelanguage'),
        ),
        migrations.RunPython(seed_tech_spec_vocab, reverse_noop),
    ]
