export const TN_PROFESSIONS = [
  // General Professions
  "Accountant",
  "Architect",
  "Computer Systems Analyst",
  "Disaster Relief Insurance Claims Adjuster",
  "Economist",
  "Engineer - Aerospace",
  "Engineer - Agricultural",
  "Engineer - Biomedical",
  "Engineer - Chemical",
  "Engineer - Civil",
  "Engineer - Computer",
  "Engineer - Electrical",
  "Engineer - Electronic",
  "Engineer - Environmental",
  "Engineer - Industrial",
  "Engineer - Mechanical",
  "Engineer - Nuclear",
  "Engineer - Petroleum",
  "Engineer - Software",
  "Engineer - Structural",
  "Forester / Sylviculturist",
  "Graphic Designer",
  "Hotel Manager",
  "Industrial Designer",
  "Interior Designer",
  "Land Surveyor",
  "Landscape Architect",
  "Lawyer / Attorney",
  "Librarian",
  "Management Consultant",
  "Mathematician",
  "Research Assistant (Post-Secondary)",
  "Scientific Technician / Technologist",
  "Social Worker",
  "Statistician",
  "Technical Publications Writer",
  "Urban Planner / Geographer",
  "Vocational Counselor",
  // Medical / Health Care
  "Dentist",
  "Dietitian",
  "Medical Laboratory Technologist",
  "Nutritionist",
  "Occupational Therapist",
  "Pharmacist",
  "Physical Therapist / Physiotherapist",
  "Physician (Teaching or Research Only)",
  "Psychologist",
  "Recreational Therapist",
  "Registered Nurse",
  "Veterinarian",
  // Scientists
  "Agriculturist / Agronomist",
  "Animal Breeder",
  "Animal Scientist",
  "Apiculturist",
  "Astronomer",
  "Biochemist / Biophysicist",
  "Biologist",
  "Chemist",
  "Dairy Scientist",
  "Entomologist",
  "Epidemiologist",
  "Geneticist",
  "Geochemist",
  "Geologist",
  "Geophysicist",
  "Horticulturist",
  "Meteorologist",
  "Pharmacologist",
  "Physicist",
  "Plant Breeder",
  "Poultry Scientist",
  "Range Manager / Conservationist",
  "Soil Scientist",
  "Zoologist / Wildlife Biologist",
  // Teachers
  "College Teacher",
  "Seminary Teacher",
  "University Teacher",
].map((p) => ({ value: p, label: p }));

export const CITIZENSHIP_OPTIONS = [
  { value: "Canadian", label: "Canadian" },
  { value: "Mexican", label: "Mexican" },
];
