import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer';
import type { TailoredBullet } from './applications';

const CATEGORY_LABELS: Record<string, string> = {
  impact: 'Impact',
  technical: 'Technical',
  leadership: 'Leadership',
  collaboration: 'Collaboration',
  other: 'Other',
};

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: '#111827',
    paddingTop: 48,
    paddingBottom: 48,
    paddingHorizontal: 52,
    lineHeight: 1.5,
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 12,
  },
  name: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: '#111827',
    marginBottom: 4,
  },
  meta: {
    fontSize: 9,
    color: '#6b7280',
    flexDirection: 'row',
    gap: 10,
  },
  metaSep: {
    color: '#d1d5db',
  },
  section: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 3,
  },
  categoryTitle: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    color: '#374151',
    marginTop: 8,
    marginBottom: 4,
  },
  bullet: {
    flexDirection: 'row',
    marginBottom: 4,
    paddingLeft: 4,
  },
  bulletDot: {
    width: 14,
    fontSize: 10,
    color: '#06b6d4',
    flexShrink: 0,
  },
  bulletText: {
    flex: 1,
    fontSize: 10,
    color: '#111827',
    lineHeight: 1.5,
  },
  footer: {
    position: 'absolute',
    bottom: 28,
    left: 52,
    right: 52,
    fontSize: 8,
    color: '#9ca3af',
    textAlign: 'center',
  },
});

export interface ResumePDFProps {
  fullName: string;
  email: string;
  jobTitle: string;
  targetRole: string;
  targetCompany: string;
  tailoredBullets: TailoredBullet[];
}

function groupByCategory(bullets: TailoredBullet[]): Map<string, TailoredBullet[]> {
  const map = new Map<string, TailoredBullet[]>();
  for (const b of bullets) {
    const cat = b.category || 'other';
    if (!map.has(cat)) map.set(cat, []);
    map.get(cat)!.push(b);
  }
  return map;
}

export function ResumeDocument({
  fullName,
  email,
  jobTitle,
  targetRole,
  targetCompany,
  tailoredBullets,
}: ResumePDFProps) {
  const grouped = groupByCategory(tailoredBullets);
  const categories = Array.from(grouped.keys());

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.name}>{fullName}</Text>
          <View style={styles.meta}>
            {jobTitle ? (
              <>
                <Text>{jobTitle}</Text>
                <Text style={styles.metaSep}>·</Text>
              </>
            ) : null}
            <Text>{email}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>
            Experience — {targetRole} at {targetCompany}
          </Text>

          {categories.map((cat) => (
            <View key={cat}>
              <Text style={styles.categoryTitle}>
                {CATEGORY_LABELS[cat] ?? cat}
              </Text>
              {grouped.get(cat)!.map((b) => (
                <View key={b.id} style={styles.bullet}>
                  <Text style={styles.bulletDot}>•</Text>
                  <Text style={styles.bulletText}>{b.tailored_text}</Text>
                </View>
              ))}
            </View>
          ))}
        </View>

        <Text style={styles.footer} fixed>
          Generated by EdgeFolio
        </Text>
      </Page>
    </Document>
  );
}
