# Generated by Django 5.2.11 on 2026-07-28 06:56

import colorfield.fields
import core.fields
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('fit', models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('image', core.fields.ResizedImageField(blank=True, max_size=[1200, None], null=True, upload_to=core.models.picture)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('date', models.DateField(help_text='The day of the encounter.')),
                ('time', models.TimeField(blank=True, help_text='Time of day, if it was noted.', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in degrees Celsius.', max_digits=5, null=True)),
                ('individuals', models.PositiveSmallIntegerField(blank=True, help_text='How many were seen, if counted.', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings', to='catalog.location')),
                ('season', models.ForeignKey(blank=True, help_text='Filled from `date` on save when left blank - see save().', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings', to='catalog.season')),
                ('species', models.ForeignKey(help_text='What was seen. PROTECT: a species with recorded sightings cannot be deleted out from under them.', on_delete=django.db.models.deletion.PROTECT, related_name='sightings', to='catalog.species')),
                ('weather', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings', to='catalog.weathercondition')),
            ],
            options={
                'verbose_name': 'Sighting',
                'verbose_name_plural': 'Sightings',
                'ordering': ['-date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='SightingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('fit', models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('image', core.fields.ResizedImageField(blank=True, max_size=[1200, None], null=True, upload_to=core.models.picture)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video file'), ('link', 'Video link')], default='image', max_length=8)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.video)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('poster', core.fields.ResizedImageField(blank=True, max_size=[512, None], null=True, upload_to=core.models.picture)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='journal.sighting')),
            ],
            options={
                'verbose_name': 'Sighting Media',
                'verbose_name_plural': 'Sighting Media',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='sighting',
            index=models.Index(fields=['-date'], name='journal_sig_date_9c0bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='sighting',
            index=models.Index(fields=['species', '-date'], name='journal_sig_species_4f7eb8_idx'),
        ),
    ]
