# Generated by Django 5.2.11 on 2026-07-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='en_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='en_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sighting',
            name='en_short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sightingmedia',
            name='en_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sightingmedia',
            name='en_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sightingmedia',
            name='en_short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
