# Generated by Django 5.2.11 on 2026-07-29 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_species_created_by_species_is_contribution_and_more'),
        ('journal', '0003_copy_existing_copy_to_english'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='author_anonymous',
            field=models.BooleanField(default=False, help_text='Withhold the credit line. The name and account are still stored - this only stops them being published.'),
        ),
        migrations.AddField(
            model_name='sighting',
            name='author_name',
            field=models.CharField(blank=True, default='', help_text='The credit line rendered under the entry ("Photographed by "). Free text, not the account name: an author may be crediting someone else. Blank means no credit is shown.', max_length=120),
        ),
        migrations.AddField(
            model_name='sighting',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The account that filed this entry. Null for entries authored in the CMS before contributions existed, and for any the author was deleted from. Never published.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_sightings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sighting',
            name='is_contribution',
            field=models.BooleanField(default=False, help_text='Filed through the public contribute flow rather than the CMS. Such an entry starts disabled and is published by an administrator enabling it.'),
        ),
        migrations.AddIndex(
            model_name='sighting',
            index=models.Index(fields=['created_by', '-date'], name='journal_sig_created_9babb7_idx'),
        ),
    ]
