# Generated by Django 5.2.11 on 2026-07-30 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Drop the stored credit line; it is derived from ``created_by`` now.

    ⚠ **This destroys whatever was typed into ``author_name``, and nothing
    migrates it** - there is nowhere for it to go. A free-text name is not an
    account, so it cannot be resolved back into one: the entries that carry a
    name a contributor filed are already the ones whose ``created_by`` supplies
    the same person's first name, and the rest (CMS entries, and anyone who
    credited a friend) simply lose their byline. Take a backup first if any of
    those matter.
    """

    dependencies = [
        ('journal', '0004_sighting_author_anonymous_sighting_author_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='sighting',
            name='author_anonymous',
            field=models.BooleanField(default=False, help_text="Withhold the credit line. The account is still recorded - this only stops the contributor's first name being published."),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The account that filed this entry, and whose first name is published as the credit line. Null for entries authored in the CMS and for any whose author was deleted - those carry no credit line at all.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_sightings', to=settings.AUTH_USER_MODEL),
        ),
    ]
