# Generated by Django 5.2.11 on 2026-07-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_remove_sighting_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightingmedia',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sightingmedia',
            name='processing_error',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='sightingmedia',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Awaiting upload'), ('processing', 'Transcoding'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=12),
        ),
        migrations.AddField(
            model_name='sightingmedia',
            name='size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sightingmedia',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
