# Generated by Django 5.2.11 on 2026-08-06 23:06
#
# The journal's half of the same backfill catalog/0015 does - see the note there.
# Every entry already on the site has been published by definition, and without
# this every one of them would read as awaiting its first review in the
# contributor's own list.

from django.db import migrations, models


def backfill(apps, schema_editor):
    apps.get_model('journal', 'Sighting').objects.filter(enabled=True).update(
        was_published=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_drop_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='was_published',
            field=models.BooleanField(default=False, help_text='Whether an administrator has ever published this row. Set the first time it is saved enabled and never cleared, so a contribution awaiting its first review can be told apart from a published one its author has edited back into review.'),
        ),
        # Reversing only drops the column, so the backfill has nothing to undo.
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
