# Generated by Django 5.2.11 on 2026-03-09 19:43

import colorfield.fields
import core.fields
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productcategory_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='background_color',
            field=colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='fit',
            field=models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='href',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[1200, None], null=True, upload_to=core.models.picture),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='background_color',
            field=colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='fit',
            field=models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='href',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[1200, None], null=True, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
