# Generated by Django 5.2.11 on 2026-03-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productcategory_background_color_productcategory_fit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='en_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='en_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
