# Generated by Django 5.2.11 on 2026-03-11 06:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productvariant_productvariantimage_variantoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(default=False, help_text='The variant pre-selected in the UI. Only one per parent should be default.'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='option_values',
            field=models.ManyToManyField(blank=True, help_text='One value per VariantOption dimension (e.g. Size=Large, Color=Brown)', to='catalog.variantoptionvalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='is_default',
            field=models.BooleanField(default=False, help_text='The variant pre-selected in the UI. Only one per parent should be default.'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='option_values',
            field=models.ManyToManyField(blank=True, help_text='One value per VariantOption dimension (e.g. Size=Large, Color=Brown)', to='catalog.variantoptionvalue'),
        ),
    ]
