# Generated by Django 5.2.11 on 2026-03-23 21:59

import core.fields
import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[512, None], null=True, quality=90, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[512, None], null=True, quality=90, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[512, None], null=True, quality=90, upload_to=core.models.picture),
        ),
    ]
