# Generated by Django 5.2.11 on 2026-03-23 22:07

import core.fields
import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[900, None], null=True, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[900, None], null=True, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[900, None], null=True, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[900, None], null=True, upload_to=core.models.picture),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[900, None], null=True, upload_to=core.models.picture),
        ),
    ]
