# Generated by Django 5.2.11 on 2026-07-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_is_ai_generated_product_is_verified_service_is_ai_generated_service_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_link',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo or direct video URL rendered as a hero above the detail page.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='video_link',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo or direct video URL rendered as a hero above the detail page.', max_length=255, null=True),
        ),
    ]
