# Generated by Django 5.2.11 on 2026-07-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_menucategory_menuitem_menuitemimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_organic',
            field=models.BooleanField(default=False),
        ),
    ]
