# Generated by Django 5.2.11 on 2026-07-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_menucategory_parent_alter_menucategory_system_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='calories',
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='kcal contributed by one unit of this ingredient.', null=True),
        ),
    ]
