# Generated by Django 5.2.11 on 2026-07-18 23:55

import colorfield.fields
import core.fields
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_menuitem_calories_menuitemingredient_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemingredient',
            name='background_color',
            field=colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='en_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='en_short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='fit',
            field=models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='href',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='image',
            field=core.fields.ResizedImageField(blank=True, max_size=[256, None], null=True, upload_to=core.models.picture),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
