# Generated by Django 5.2.11 on 2026-07-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_menuitemingredient_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemingredient',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
