# Generated by Django 5.2.11 on 2026-07-19 02:16

import colorfield.fields
import core.fields
import core.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def purge_menu_item_ingredients(apps, schema_editor):
    """Destructive, pre-launch: drop existing rows so the new non-null
    ``ingredient`` FK can be added. Ingredient identity/nutrition previously
    lived inline on each row and is intentionally not backfilled - menu items
    are re-linked against the new Ingredient catalog by hand."""
    apps.get_model('catalog', 'MenuItemIngredient').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_menuitem_show_nutrition_label'),
        ('core', '0025_alter_brand_system_alter_companyhighlight_system_and_more'),
    ]

    operations = [
        migrations.RunPython(purge_menu_item_ingredients, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='menuitemingredient',
            options={'ordering': ['sort_order', 'ingredient__name'], 'verbose_name': 'Menu Item Ingredient', 'verbose_name_plural': 'Menu Item Ingredients'},
        ),
        migrations.RemoveField(
            model_name='menuitemingredient',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='menuitemingredient',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='menuitemingredient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitemingredient',
            name='en_description',
        ),
        migrations.RemoveField(
            model_name='menuitemingredient',
            name='en_name',
        ),
        migrations.RemoveField(
            model_name='menuitemingredient',
            name='en_short_description',
        ),
        migrations.RemoveField(
            model_name='menuitemingredient',
            name='fit',
        ),
        migrations.RemoveField(
            model_name='menuitemingredient',
            name='href',
        ),
        migrations.RemoveField(
            model_name='menuitemingredient',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menuitemingredient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='menuitemingredient',
            name='short_description',
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('en_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('en_description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('en_short_description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('fit', models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('image', core.fields.ResizedImageField(blank=True, max_size=[256, None], null=True, upload_to=core.models.picture)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('mg', 'Milligrams'), ('ml', 'Milliliters'), ('l', 'Liters'), ('oz', 'Ounces'), ('lb', 'Pounds'), ('cup', 'Cups'), ('tbsp', 'Tablespoons'), ('tsp', 'Teaspoons'), ('pc', 'Pieces'), ('slice', 'Slices'), ('scoop', 'Scoops')], max_length=8)),
                ('nutrition_basis_quantity', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='The nutrition values below are stated per this many `unit` (e.g. 100 for "per 100 g", 1 for "per piece").', max_digits=10)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, help_text='kcal.', max_digits=8, null=True)),
                ('total_fat', models.DecimalField(blank=True, decimal_places=2, help_text='grams.', max_digits=8, null=True)),
                ('saturated_fat', models.DecimalField(blank=True, decimal_places=2, help_text='grams.', max_digits=8, null=True)),
                ('trans_fat', models.DecimalField(blank=True, decimal_places=2, help_text='grams.', max_digits=8, null=True)),
                ('cholesterol', models.DecimalField(blank=True, decimal_places=2, help_text='milligrams.', max_digits=8, null=True)),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, help_text='milligrams.', max_digits=8, null=True)),
                ('total_carbohydrate', models.DecimalField(blank=True, decimal_places=2, help_text='grams.', max_digits=8, null=True)),
                ('dietary_fiber', models.DecimalField(blank=True, decimal_places=2, help_text='grams.', max_digits=8, null=True)),
                ('total_sugars', models.DecimalField(blank=True, decimal_places=2, help_text='grams.', max_digits=8, null=True)),
                ('added_sugars', models.DecimalField(blank=True, decimal_places=2, help_text='grams.', max_digits=8, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, help_text='grams.', max_digits=8, null=True)),
                ('vitamin_d', models.DecimalField(blank=True, decimal_places=2, help_text='micrograms.', max_digits=8, null=True)),
                ('calcium', models.DecimalField(blank=True, decimal_places=2, help_text='milligrams.', max_digits=8, null=True)),
                ('iron', models.DecimalField(blank=True, decimal_places=2, help_text='milligrams.', max_digits=8, null=True)),
                ('potassium', models.DecimalField(blank=True, decimal_places=2, help_text='milligrams.', max_digits=8, null=True)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.system')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='menu_uses', to='catalog.ingredient'),
            preserve_default=False,
        ),
    ]
