# Generated by Django 5.2.11 on 2026-07-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_menuitem_portions_ingredient_removable_semantics'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemingredient',
            name='default_quantity',
            field=models.PositiveSmallIntegerField(default=0, help_text='Quantity pre-selected for the customer in the stepper (and the baseline a "no change" selection is measured against). Must be ≤ max_quantity. Ignored for a non-removable ingredient, which is locked at its single portion.'),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='number_of_free_portions',
            field=models.PositiveSmallIntegerField(default=0, help_text='Units the customer gets at no charge before the per-unit price applies. Must be ≤ max_quantity. Only meaningful for a removable add-on; a non-removable ingredient is always its single included portion regardless.'),
        ),
    ]
