# Generated by Django 5.2.11 on 2026-07-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_menuitemingredient_default_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemingredient',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Internal recipe-only component. Hidden from the customer customiser and excluded from the price, but still counted in the public nutrition label (it is really in the food). For kitchen/recipe use, e.g. cooking oil or a seasoning base.'),
        ),
    ]
