# Generated by Django 5.2.11 on 2026-07-19 20:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_menuitemingredient_is_internal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemIngredientOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Up-charge per unit when this option is chosen.', max_digits=12)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_option_uses', to='catalog.ingredient')),
                ('menu_item_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.menuitemingredient')),
            ],
            options={
                'verbose_name': 'Menu Item Ingredient Option',
                'verbose_name_plural': 'Menu Item Ingredient Options',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
