# Generated by Django 5.2.11 on 2026-07-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_menuitemingredientoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemingredient',
            name='group_en_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='group_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
