# Generated by Django 5.2.11 on 2026-07-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_menuitemingredient_group_en_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='variants',
            field=models.ManyToManyField(blank=True, help_text='Other menu items that are alternative versions of this dish (vegan, gluten-free, a different size, etc.). Shown as choices on the public detail page. The link is mutual - adding it from one item surfaces it on the other too.', to='catalog.menuitem'),
        ),
    ]
