# Generated by Django 5.2.11 on 2026-07-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_menuitem_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('MXN', 'Mexican Peso'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('ARS', 'Argentine Peso'), ('COP', 'Colombian Peso'), ('CLP', 'Chilean Peso'), ('BRL', 'Brazilian Real')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for `nutrition_basis_quantity` of `unit`. Blank = unpriced.', max_digits=12, null=True),
        ),
    ]
