# Generated by Django 5.2.11 on 2026-07-20 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_ingredient_currency_ingredient_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Store or supplier name, e.g. "Costco".', max_length=255, null=True)),
                ('url', models.URLField(max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="This provider's quoted price. Blank = unquoted.", max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('MXN', 'Mexican Peso'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('ARS', 'Argentine Peso'), ('COP', 'Colombian Peso'), ('CLP', 'Chilean Peso'), ('BRL', 'Brazilian Real')], default='USD', max_length=3)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='catalog.ingredient')),
            ],
            options={
                'verbose_name': 'Ingredient Provider',
                'verbose_name_plural': 'Ingredient Providers',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
