# Generated by Django 5.2.11 on 2026-07-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_ingredientprovider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Menu Category', 'verbose_name_plural': 'Menu Categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['sort_order', '-created'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', '-created'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['sort_order', '-created'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='variantoption',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Variant Option', 'verbose_name_plural': 'Variant Options'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
