# Generated by Django 5.2.11 on 2026-07-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_alter_ingredient_options_alter_menucategory_options_and_more'),
    ]

    operations = [
        # Must precede the RemoveField below: on SQLite a column drop remakes the
        # whole table, and the remake fails while unique_together still names the
        # `option` field being dropped.
        migrations.AlterUniqueTogether(
            name='variantoptionvalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='option_values',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariantimage',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='servicevariant',
            name='option_values',
        ),
        migrations.RemoveField(
            model_name='servicevariant',
            name='service',
        ),
        migrations.RemoveField(
            model_name='variantoption',
            name='system',
        ),
        migrations.RemoveField(
            model_name='variantoptionvalue',
            name='option',
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(blank=True, help_text='Other products that are alternative versions of this one (a different size, color, material, etc.). Shown as choices on the public detail page. The link is mutual - adding it from one product surfaces it on the other too.', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='service',
            name='variants',
            field=models.ManyToManyField(blank=True, help_text='Other services that are alternative versions of this one (a different duration, modality, package, etc.). Shown as choices on the public detail page. The link is mutual - adding it from one service surfaces it on the other too.', to='catalog.service'),
        ),
    ]
