# Generated by Django 5.2.11 on 2026-07-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_remove_productvariant_option_values_and_more'),
        ('orders', '0005_remove_orderline_product_variant_and_more'),
        ('users', '0011_remove_cartitem_unique_user_product_variant_cart_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='ProductVariantImage',
        ),
        migrations.DeleteModel(
            name='ServiceVariant',
        ),
        migrations.DeleteModel(
            name='VariantOption',
        ),
        migrations.DeleteModel(
            name='VariantOptionValue',
        ),
    ]
