# Generated by Django 5.2.11 on 2026-07-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_delete_productvariant_delete_productvariantimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='kind',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('dessert', 'Dessert'), ('side', 'Side'), ('appetizer', 'Appetizer')], default='food', help_text='What this item is - drives menu sections, filters and the storefront (e.g. a bar/drinks list).', max_length=16),
        ),
    ]
