# Generated by Django 5.2.11 on 2026-08-03 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_menuitem_kind'),
        ('core', '0055_branch_booking_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='booking_branches',
            field=models.ManyToManyField(blank=True, help_text='Locations this service can be booked at. Leave empty to offer every location.', related_name='bookable_services', to='core.branch'),
        ),
        migrations.AddField(
            model_name='service',
            name='booking_deposit_percent',
            field=models.PositiveSmallIntegerField(default=30, help_text='Percentage charged up front when paying a deposit.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='service',
            name='booking_enabled',
            field=models.BooleanField(default=False, help_text='Sell this service as a scheduled appointment instead of a cart item.'),
        ),
        migrations.AddField(
            model_name='service',
            name='booking_in_branch',
            field=models.BooleanField(default=True, help_text='Can be fulfilled at one of the business locations.'),
        ),
        migrations.AddField(
            model_name='service',
            name='booking_on_premises',
            field=models.BooleanField(default=False, help_text="Can be fulfilled at the customer's own address."),
        ),
        migrations.AddField(
            model_name='service',
            name='booking_pay_deposit',
            field=models.BooleanField(default=False, help_text='Customer pays a percentage online to secure the booking; the rest is due later.'),
        ),
        migrations.AddField(
            model_name='service',
            name='booking_pay_full',
            field=models.BooleanField(default=False, help_text='Customer pays the full price online to confirm the booking.'),
        ),
        migrations.AddField(
            model_name='service',
            name='booking_pay_in_person',
            field=models.BooleanField(default=True, help_text='Customer pays nothing now; the service is paid once delivered.'),
        ),
    ]
