# Generated by Django 5.2.11 on 2026-08-08 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_service_booking_branches_and_more'),
        ('core', '0057_alter_branch_booking_capacity_resourcepool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='booking_party_enabled',
            field=models.BooleanField(default=False, help_text='One booking can cover several people (price is per person).'),
        ),
        migrations.AddField(
            model_name='service',
            name='booking_party_max',
            field=models.PositiveSmallIntegerField(default=10, help_text='Largest party this service accepts (still capped by what a resource holds).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='service',
            name='booking_party_min',
            field=models.PositiveSmallIntegerField(default=1, help_text='Smallest party this service accepts.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='service',
            name='booking_pools',
            field=models.ManyToManyField(blank=True, help_text='Which resources this service uses. Leave empty to use every pool at the location.', related_name='services', to='core.resourcepool'),
        ),
    ]
