# Generated by Django 5.2.11 on 2026-08-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_service_booking_party_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='eta_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated time until this item is ready, in minutes.', null=True),
        ),
    ]
