# Generated by Django 5.2.11 on 2026-08-17 07:21

import colorfield.fields
import core.fields
import core.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_ingredient_attribution_ingredient_attribution_url_and_more'),
        ('core', '0067_companyhighlight_attribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='sizes_enabled',
            field=models.BooleanField(default=True, help_text="Offer this dish in several sizes (its own if it has any, otherwise its category's). Off: sold in one size."),
        ),
        migrations.CreateModel(
            name='MenuSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('en_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('en_description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('en_short_description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('attribution', models.CharField(blank=True, default='', max_length=255)),
                ('attribution_url', models.URLField(blank=True, default='', max_length=500)),
                ('fit', models.CharField(blank=True, choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill'), ('scale-down', 'Scale Down'), ('none', 'None')], default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('image', core.fields.ResizedImageField(blank=True, max_size=[256, None], null=True, upload_to=core.models.picture)),
                ('name', models.CharField(max_length=255)),
                ('portion', models.DecimalField(blank=True, decimal_places=2, help_text='How big this size is, in `unit` (e.g. 12 for a 12-inch pizza). Descriptive - nothing is computed from it.', max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, choices=[('in', 'Inches'), ('cm', 'Centimeters'), ('mm', 'Millimeters'), ('ml', 'Milliliters'), ('l', 'Liters'), ('oz', 'Ounces'), ('g', 'Grams'), ('kg', 'Kilograms'), ('lb', 'Pounds'), ('pc', 'Pieces'), ('slice', 'Slices')], max_length=8, null=True)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Added to the item base price when this size is chosen. Negative discounts it (a small size), positive adds to it.', max_digits=12)),
                ('is_default', models.BooleanField(default=False, help_text='Pre-selected for the customer. With none flagged, the first size in display order is used.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalog.menucategory')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_sizes', to='catalog.menuitem')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_sizes', to='core.system')),
            ],
            options={
                'verbose_name': 'Menu Size',
                'verbose_name_plural': 'Menu Sizes',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('menu_item__isnull', True)), models.Q(('category__isnull', True), ('menu_item__isnull', False)), _connector='OR'), name='menu_size_exactly_one_owner')],
            },
        ),
    ]
