# Generated by Django 5.2.11 on 2026-08-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_menuitem_sizes_enabled_menusize'),
        ('core', '0067_companyhighlight_attribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('menu_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='catalog.menucategory')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_recommendations', to='catalog.menuitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_recommendations', to='catalog.product')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='catalog.productcategory')),
                ('recommended_menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by', to='catalog.menuitem')),
                ('recommended_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by', to='catalog.product')),
                ('recommended_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by', to='catalog.service')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_recommendations', to='catalog.service')),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='catalog.servicecategory')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_recommendations', to='core.system')),
            ],
            options={
                'verbose_name': 'Checkout Recommendation',
                'verbose_name_plural': 'Checkout Recommendations',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('service__isnull', True), ('menu_item__isnull', True), ('product_category__isnull', True), ('service_category__isnull', True), ('menu_category__isnull', True)), models.Q(('service__isnull', False), ('product__isnull', True), ('menu_item__isnull', True), ('product_category__isnull', True), ('service_category__isnull', True), ('menu_category__isnull', True)), models.Q(('menu_item__isnull', False), ('product__isnull', True), ('service__isnull', True), ('product_category__isnull', True), ('service_category__isnull', True), ('menu_category__isnull', True)), models.Q(('product_category__isnull', False), ('product__isnull', True), ('service__isnull', True), ('menu_item__isnull', True), ('service_category__isnull', True), ('menu_category__isnull', True)), models.Q(('service_category__isnull', False), ('product__isnull', True), ('service__isnull', True), ('menu_item__isnull', True), ('product_category__isnull', True), ('menu_category__isnull', True)), models.Q(('menu_category__isnull', False), ('product__isnull', True), ('service__isnull', True), ('menu_item__isnull', True), ('product_category__isnull', True), ('service_category__isnull', True)), _connector='OR'), name='catalog_recommendation_exactly_one_source'), models.CheckConstraint(condition=models.Q(models.Q(('recommended_product__isnull', False), ('recommended_service__isnull', True), ('recommended_menu_item__isnull', True)), models.Q(('recommended_service__isnull', False), ('recommended_product__isnull', True), ('recommended_menu_item__isnull', True)), models.Q(('recommended_menu_item__isnull', False), ('recommended_product__isnull', True), ('recommended_service__isnull', True)), _connector='OR'), name='catalog_recommendation_exactly_one_target')],
            },
        ),
    ]
