# Generated by Django 5.2.11 on 2026-08-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_catalogrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='points_award',
            field=models.PositiveIntegerField(blank=True, help_text='Points earned per unit for items in this category. Blank means none.', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='points_award',
            field=models.PositiveIntegerField(blank=True, help_text="Points earned per unit bought. Blank inherits the category's.", null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='points_price',
            field=models.PositiveIntegerField(blank=True, help_text='Points needed to buy one of these. Blank means it cannot be bought with points.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='points_award',
            field=models.PositiveIntegerField(blank=True, help_text="Points earned per unit bought. Blank inherits the category's.", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='points_price',
            field=models.PositiveIntegerField(blank=True, help_text='Points needed to buy one of these. Blank means it cannot be bought with points.', null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='points_award',
            field=models.PositiveIntegerField(blank=True, help_text='Points earned per unit for items in this category. Blank means none.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='points_award',
            field=models.PositiveIntegerField(blank=True, help_text="Points earned per unit bought. Blank inherits the category's.", null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='points_price',
            field=models.PositiveIntegerField(blank=True, help_text='Points needed to buy one of these. Blank means it cannot be bought with points.', null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='points_award',
            field=models.PositiveIntegerField(blank=True, help_text='Points earned per unit for items in this category. Blank means none.', null=True),
        ),
    ]
