# Generated by Django 5.2.11 on 2026-08-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_product_service_category_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='menuitemimage',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='menusize',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='productimage',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='service',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', 'Auto - from the images'), ('4:5', 'Portrait (4:5)'), ('5:4', 'Landscape (5:4)'), ('1:1', 'Square (1:1)'), ('16:9', 'Wide (16:9)'), ('3:2', 'Photo (3:2)'), ('9:16', 'Tall (9:16)')], default='', max_length=16),
        ),
    ]
