# Generated by Django 4.1.9 on 2023-06-29 00:16

import common.models.picture
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stand', '0002_stand_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('full_size', models.BooleanField(default=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, scale=None, size=[1080, 1080], upload_to=common.models.picture.picture)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('publish_on_the_wall', models.BooleanField(default=False, verbose_name='Publicar en el muro')),
                ('state', models.CharField(blank=True, choices=[('new', 'new'), ('like-new', 'like-new'), ('used', 'used')], default='new', max_length=16, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=5, help_text='Precio del producto', max_digits=10, verbose_name='Precio del producto')),
                ('discount', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Descuento de 1% a 99%', null=True, verbose_name='Descuento')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio final')),
                ('brand', models.CharField(blank=True, help_text='Marca del producto', max_length=64, null=True, verbose_name='Marca')),
                ('short_description', models.CharField(blank=True, help_text='Descripción corta (90 carácteres)', max_length=90, null=True, verbose_name='Descripción corta')),
                ('unlimited_stock', models.BooleanField(default=False, verbose_name='Stock ilimitado?')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, help_text='Cantidad de producto que existe en stock', null=True, verbose_name='Cantidad de producto')),
                ('shipping_cost', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Costo de envío')),
                ('video_link', models.CharField(blank=True, help_text='Link del vídeo de youtube', max_length=512, null=True, verbose_name='Link del vídeo')),
                ('support_email', models.EmailField(blank=True, help_text='Correo electrónico de soporte', max_length=128, null=True, verbose_name='Correo de soporte')),
                ('support_info', models.CharField(blank=True, help_text='Información de soporte', max_length=256, null=True, verbose_name='Información de soporte')),
                ('support_phone', models.CharField(blank=True, help_text='Teléfono de soporte', max_length=12, null=True, verbose_name='Teléfono de soporte')),
                ('warranty_days', models.PositiveIntegerField(blank=True, default=0, help_text='Días de garantía del producto', verbose_name='Días de garantía')),
                ('times_selled', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Cantidad de veces vendido')),
                ('views', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Cantidad de veces visto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductDeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('full_size', models.BooleanField(default=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, scale=None, size=[512, 512], upload_to=common.models.picture.picture)),
                ('name', models.CharField(max_length=64)),
                ('icon', models.CharField(blank=True, help_text='Ícono', max_length=32, null=True, verbose_name='Ícono')),
            ],
            options={
                'verbose_name': 'Tipo de envío',
                'verbose_name_plural': 'Tipos de envíos',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Caracteristica del producto',
                'verbose_name_plural': 'Caracteristicas de los productos',
            },
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('full_size', models.BooleanField(default=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, scale=None, size=[512, 512], upload_to=common.models.picture.picture)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Producto')),
                ('stand', models.ForeignKey(help_text='Empresa al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, to='stand.stand', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Foto del producto',
                'verbose_name_plural': 'Fotos de los productos',
            },
        ),
        migrations.CreateModel(
            name='ProductFeatureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('feature', models.ForeignKey(help_text='Caracteristica del producto', on_delete=django.db.models.deletion.CASCADE, to='product.productfeature', verbose_name='Caracteristica del producto')),
            ],
            options={
                'verbose_name': 'Opcion de caracteristica del producto',
                'verbose_name_plural': 'Opciones de caracteristicas del producto',
            },
        ),
        migrations.AddField(
            model_name='productfeature',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='product_feature_options', to='product.productfeatureoption', verbose_name='Opciones de caractarísticas del producto'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='stand',
            field=models.ForeignKey(help_text='Empresa al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='stand_product_feature', to='stand.stand', verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='ProductClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('full_size', models.BooleanField(default=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, scale=None, size=[512, 512], upload_to=common.models.picture.picture)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('stand', models.ForeignKey(help_text='Empresa al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='stand_product_classification', to='stand.stand', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de productos',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='classification',
            field=models.ForeignKey(help_text='Clasificación al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productclassification', verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_type',
            field=models.ManyToManyField(blank=True, help_text='Tipo de entrega', related_name='delivery_type', to='product.productdeliverytype', verbose_name='Tipo de entrega'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='product_features', to='product.productfeatureoption', verbose_name='Caractarísticas del producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pictures',
            field=models.ManyToManyField(blank=True, help_text='Fotos del producto', related_name='product_pictures', to='product.productpicture', verbose_name='Fotos'),
        ),
        migrations.AddField(
            model_name='product',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='related_products', to='product.product', verbose_name='Productos relacionados'),
        ),
        migrations.AddField(
            model_name='product',
            name='stand',
            field=models.ForeignKey(help_text='Empresa al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stand_product', to='stand.stand', verbose_name='Empresa'),
        ),
    ]
