# Generated by Django 5.0.6 on 2024-06-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(blank=True, default='new', max_length=16, null=True),
        ),
    ]
