# Generated by Django 5.0.6 on 2024-06-22 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_state'),
        ('stand', '0006_alter_standphone_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productclassification', verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stand_product', to='stand.stand', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='productfeatureoption',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
