# Generated by Django 5.0.6 on 2024-06-23 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_classification_alter_product_stand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeatureoption',
            name='feature',
            field=models.ForeignKey(help_text='Caracteristica del producto', on_delete=django.db.models.deletion.CASCADE, related_name='option_product_feature', to='product.productfeature', verbose_name='Caracteristica del producto'),
        ),
    ]
