replicaCount: 1
webAppName: default
volumeMountPath: "shared-volume"

image:
  registry: docker.io
  repository: nginx
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enabled: false
  host: basic-go-rest-api.iguzman.com.mx

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
