replicaCount: 1
volumeMountPath: "shared-volume"
nginxServiceName: "nginx-web-app"
branch: "main"

image:
  registry: christopherguzman
  repository: plant
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000

ingress:
  enabled: false
  host: myapp.com

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

deployment:
  nodeSelector:
    nodeProjects: real-clients
