# Generated by Django 4.1.9 on 2023-06-28 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_nediiplan'),
        ('stand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.nediiplan'),
            preserve_default=False,
        ),
    ]
