# Generated by Django 4.1.9 on 2023-06-28 22:43

import common.models.picture
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stand', '0002_stand_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('href', models.URLField(blank=True, null=True)),
                ('full_size', models.BooleanField(default=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, scale=None, size=[512, 512], upload_to=common.models.picture.picture)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('publish_on_the_wall', models.BooleanField(default=False, verbose_name='Publicar en el muro')),
                ('stock', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Cantidad que existe en stock', null=True, verbose_name='Cantidad en Stock')),
                ('is_breakfast', models.BooleanField(default=False, verbose_name='Es desayuno')),
                ('is_meal', models.BooleanField(default=True, verbose_name='Es comida')),
                ('is_dinner', models.BooleanField(default=False, verbose_name='Es cena')),
                ('short_description', models.CharField(blank=True, help_text='Descripción corta (90 carácteres)', max_length=90, null=True, verbose_name='Descripción corta')),
                ('description', models.TextField(blank=True, default='Descripcion del platillo', null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, default=5, help_text='Precio del platillo', max_digits=10, verbose_name='Precio del platillo')),
                ('discount', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Descuento de 1% a 99%', null=True, verbose_name='Descuento')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio final')),
                ('video_link', models.URLField(blank=True, help_text='Link del vídeo de youtube', null=True, verbose_name='Link del vídeo')),
                ('times_selled', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Cantidad de veces vendido')),
                ('views', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Cantidad de veces visto')),
            ],
            options={
                'verbose_name': 'Platillo',
                'verbose_name_plural': 'Platillos',
            },
        ),
        migrations.CreateModel(
            name='MealPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('full_size', models.BooleanField(default=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, scale=None, size=[512, 512], upload_to=common.models.picture.picture)),
                ('meal', models.ForeignKey(help_text='Platillo al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.meal', verbose_name='Platillo')),
                ('stand', models.ForeignKey(help_text='Restaurante al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, to='stand.stand', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Foto de comida',
                'verbose_name_plural': 'Fotos de comidas',
            },
        ),
        migrations.CreateModel(
            name='MealClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('full_size', models.BooleanField(default=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, scale=None, size=[512, 512], upload_to=common.models.picture.picture)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('img_icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='Icono')),
                ('stand', models.ForeignKey(help_text='Restaurante al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='stand_meal_classification', to='stand.stand', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Categoría de comida',
                'verbose_name_plural': 'Categorías de comidas',
            },
        ),
        migrations.CreateModel(
            name='MealAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('full_size', models.BooleanField(default=True)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, scale=None, size=[256, 256], upload_to=common.models.picture.picture)),
                ('name', models.CharField(max_length=64)),
                ('quantity', models.CharField(blank=True, default='1', max_length=32, verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Precio')),
                ('stand', models.ForeignKey(help_text='Restaurante al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='stand_meal_addon', to='stand.stand', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Ingrediente / adicional',
                'verbose_name_plural': 'Ingredientes / adicionales',
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='classification',
            field=models.ForeignKey(help_text='Clasificación al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.mealclassification', verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_addons',
            field=models.ManyToManyField(blank=True, help_text='Ingredientes / Adicionales', to='meal.mealaddon', verbose_name='Adicionales'),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_pictures',
            field=models.ManyToManyField(blank=True, help_text='Fotos del platillo', related_name='meal_pictures', to='meal.mealpicture', verbose_name='Fotos'),
        ),
        migrations.AddField(
            model_name='meal',
            name='stand',
            field=models.ForeignKey(help_text='Restaurante al que pertenece este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stand_meal', to='stand.stand', verbose_name='Restaurante'),
        ),
    ]
