# Generated by Django 4.1.9 on 2023-06-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_records', '0002_alter_daymeasurement_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daymeasurement',
            name='final_ram_capacity',
        ),
        migrations.RemoveField(
            model_name='daymeasurement',
            name='final_storage_capacity',
        ),
        migrations.RemoveField(
            model_name='daymeasurement',
            name='initial_ram_capacity',
        ),
        migrations.RemoveField(
            model_name='daymeasurement',
            name='initial_storage_capacity',
        ),
    ]
