# Generated by Django 4.1.9 on 2023-08-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_records', '0003_remove_daymeasurement_final_ram_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daymeasurement',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
