# Generated by Django 4.1.9 on 2023-06-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userorder_user_biography_user_is_seller_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPicture',
        ),
    ]
