# Generated by Django 4.1.9 on 2024-01-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_userpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usercartbuyableitem',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userfavoritebuyableitem',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userfavoritestand',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userorderbuyableitem',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
