# Generated by Django 5.0.6 on 2024-06-26 19:18

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useraddress_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='user_cart_items', to='users.usercartbuyableitem'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_items',
            field=models.ManyToManyField(blank=True, related_name='user_favorite_items', to='users.userfavoritebuyableitem'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_stands',
            field=models.ManyToManyField(blank=True, related_name='user_favorite_stands', to='users.userfavoritestand'),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
