# Generated by Django 5.0.6 on 2024-06-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_cart_items_user_favorite_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercartbuyableitem',
            name='backup_final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio final'),
        ),
        migrations.AlterField(
            model_name='usercartbuyableitem',
            name='backup_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nombre de elemento comprado'),
        ),
        migrations.AlterField(
            model_name='usercartbuyableitem',
            name='backup_user_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nombre del comprador'),
        ),
        migrations.AlterField(
            model_name='userfavoritebuyableitem',
            name='backup_final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio final'),
        ),
        migrations.AlterField(
            model_name='userfavoritebuyableitem',
            name='backup_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nombre de elemento comprado'),
        ),
        migrations.AlterField(
            model_name='userfavoritebuyableitem',
            name='backup_user_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nombre del comprador'),
        ),
        migrations.AlterField(
            model_name='userorderbuyableitem',
            name='backup_final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio final'),
        ),
        migrations.AlterField(
            model_name='userorderbuyableitem',
            name='backup_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nombre de elemento comprado'),
        ),
        migrations.AlterField(
            model_name='userorderbuyableitem',
            name='backup_user_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nombre del comprador'),
        ),
    ]
