# Generated by Django 4.1.9 on 2023-05-25 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_plant_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('min_soil_humidity', models.SmallIntegerField(blank=True, null=True)),
                ('min_ambient_temperature', models.SmallIntegerField(blank=True, null=True)),
                ('max_ambient_temperature', models.SmallIntegerField(blank=True, null=True)),
                ('min_ambient_humidity', models.SmallIntegerField(blank=True, null=True)),
                ('max_ambient_humidity', models.SmallIntegerField(blank=True, null=True)),
                ('min_light_value', models.SmallIntegerField(blank=True, null=True)),
                ('max_light_value', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='measurement',
            name='version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plant',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.planttype'),
        ),
    ]
