# Generated by Django 4.1.9 on 2023-05-31 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_changelog_version_alter_city_version_and_more'),
        ('records', '0009_planttype_minutes_to_upload_sensor_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.city'),
        ),
        migrations.AddField(
            model_name='plant',
            name='zip_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
