# Generated by Django 4.1.9 on 2023-06-22 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_changelog_version_alter_city_version_and_more'),
        ('records', '0012_plantcontrollertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='total_ram_capacity',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='total_storage_capacity',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='plantcontroller',
            name='max_cpu_temperature',
        ),
        migrations.RemoveField(
            model_name='plantcontroller',
            name='min_cpu_temperature',
        ),
        migrations.RemoveField(
            model_name='plantcontroller',
            name='total_ram_capacity',
        ),
        migrations.RemoveField(
            model_name='plantcontroller',
            name='total_storage_capacity',
        ),
        migrations.AddField(
            model_name='plantcontroller',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.city'),
        ),
        migrations.AddField(
            model_name='plantcontroller',
            name='cpu_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plantcontroller',
            name='plant_constroller_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.plantcontrollertype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantcontroller',
            name='ram_allocated',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='plantcontroller',
            name='storage_allocated',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='plantcontroller',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
