# Generated by Django 5.2.11 on 2026-06-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_techstack_project_tech_stack'),
        ('users', '0006_userprofile_github_url_userprofile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_stack',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_stack',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='career.techstack'),
        ),
    ]
