# Generated by Django 5.2.11 on 2026-06-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_preferred_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tn_profession',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
