# Generated by Django 5.2.11 on 2026-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_job_search_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_search_generated_query',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
