# Generated by Django 4.1.9 on 2023-06-30 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicle_year_alter_vehiclemake_name_and_more'),
        ('meal', '0001_initial'),
        ('service', '0001_initial'),
        ('real_estate', '0002_alter_realestate_year'),
        ('product', '0001_initial'),
        ('stand', '0002_stand_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expo',
            old_name='real',
            new_name='is_real',
        ),
        migrations.AddField(
            model_name='stand',
            name='highlighted_meals',
            field=models.ManyToManyField(blank=True, help_text='Platillos destacados', related_name='highlighted_meals', to='meal.meal', verbose_name='Platillos destacados'),
        ),
        migrations.AddField(
            model_name='stand',
            name='highlighted_products',
            field=models.ManyToManyField(blank=True, help_text='Productos destacados', related_name='highlighted_products', to='product.product', verbose_name='Productos destacados'),
        ),
        migrations.AddField(
            model_name='stand',
            name='highlighted_real_estates',
            field=models.ManyToManyField(blank=True, help_text='Inmuebles destacados', related_name='highlighted_real_estates', to='real_estate.realestate', verbose_name='Inmuebles destacados'),
        ),
        migrations.AddField(
            model_name='stand',
            name='highlighted_services',
            field=models.ManyToManyField(blank=True, help_text='Servicios destacados', related_name='highlighted_services', to='service.service', verbose_name='Servicios destacados'),
        ),
        migrations.AddField(
            model_name='stand',
            name='highlighted_vehicles',
            field=models.ManyToManyField(blank=True, help_text='Vehículos destacados', related_name='highlighted_vehicles', to='vehicle.vehicle', verbose_name='Vehículos destacados'),
        ),
        migrations.AddField(
            model_name='standpromotion',
            name='meal',
            field=models.ForeignKey(blank=True, help_text='Platillo de la promoción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_deal', to='meal.meal', verbose_name='Platillo'),
        ),
        migrations.AddField(
            model_name='standpromotion',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Producto de la promoción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_deal', to='product.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='standpromotion',
            name='real_estate',
            field=models.ForeignKey(blank=True, help_text='Inmueble de la promoción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_deal', to='real_estate.realestate', verbose_name='Inmueble'),
        ),
        migrations.AddField(
            model_name='standpromotion',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Servicio de la promoción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_deal', to='service.service', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='standpromotion',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehículo de la promoción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_deal', to='vehicle.vehicle', verbose_name='Vehículo'),
        ),
    ]
