# Generated by Django 5.0.6 on 2024-05-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stand', '0004_alter_expo_version_alter_group_version_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameField(
            model_name='stand',
            old_name='group',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='expo',
            name='groups',
        ),
        migrations.AddField(
            model_name='expo',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categorias de esta expo', related_name='expo_categories', to='stand.category', verbose_name='Categorias'),
        ),
    ]
