# Generated by Django 5.0.6 on 2024-06-07 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stand', '0005_rename_group_category_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standphone',
            unique_together={('stand', 'phone')},
        ),
    ]
