replicaCount: 1
volumeMountPath: "shared-volume"
nginxServiceName: "nginx-web-app"
branch: "main"

image:
  registry: christopherguzman
  repository: basic-go-rest-api
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000

ingress:
  enabled: false
  host: basic-go-rest-api.iguzman.com.mx

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
