# Generated by Django 5.2.11 on 2026-06-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_jobapplication_nafta_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='nafta_tn_likelihood',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='overall_match',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='technical_match',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
