# Generated by Django 5.2.11 on 2026-06-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_jobapplication_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company_description',
            field=models.TextField(blank=True),
        ),
    ]
