# Generated by Django 5.2.11 on 2026-06-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_jobapplication_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='nafta_tn_likelihood_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='overall_match_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='technical_match_explanation',
            field=models.TextField(blank=True),
        ),
    ]
