# Generated by Django 5.2.11 on 2026-06-10 15:14

from django.conf import settings
from django.db import migrations, models


def deduplicate_job_urls(apps, schema_editor):
    JobApplication = apps.get_model('applications', 'JobApplication')
    seen = {}
    for app in JobApplication.objects.exclude(job_url='').order_by('id'):
        key = (app.user_id, app.job_url)
        if key in seen:
            app.delete()
        else:
            seen[key] = app.id


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_jobapplication_metric_explanations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicate_job_urls, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('job_url', ''), _negated=True), fields=('user', 'job_url'), name='unique_job_application_url_per_user'),
        ),
    ]
