# Generated by Django 5.2.11 on 2026-06-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_jobapplication_unique_job_application_url_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('CAD', 'CAD'), ('EUR', 'EUR'), ('MXN', 'MXN'), ('GBP', 'GBP')], max_length=3),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='us_citizen_or_pr_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='work_type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
