# Generated by Django 5.2.11 on 2026-06-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_jobapplication_tailored_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='tailored_projects',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tailored_work_experiences',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
