# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_jobapplication_tailored_we_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company_intel',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
