# Generated by Django 5.2.11 on 2026-06-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_jobapplication_source_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='tailor_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tailor_status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], max_length=20),
        ),
    ]
