# Generated by Django 5.2.11 on 2026-06-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_jobapplication_tailor_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='language_requirement_unmet',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
