# Generated by Django 4.1.9 on 2023-05-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_rename_type_plant_plant_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='debug_measurment_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
