# Generated by Django 4.1.9 on 2023-05-27 05:03

from django.db import migrations
import django_resized.forms
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_measurement_debug_measurment_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='img_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to=records.models.picture),
        ),
        migrations.AddField(
            model_name='planttype',
            name='img_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to=records.models.picture),
        ),
    ]
