# Generated by Django 4.1.9 on 2023-06-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_plant_city_plant_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='ram_usage',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='storage_usage',
        ),
        migrations.RemoveField(
            model_name='plantcontroller',
            name='ram_capacity',
        ),
        migrations.RemoveField(
            model_name='plantcontroller',
            name='storage_capacity',
        ),
        migrations.AddField(
            model_name='measurement',
            name='ram_allocated',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='storage_allocated',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='total_ram_capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='total_storage_capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='plantcontroller',
            name='total_ram_capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='plantcontroller',
            name='total_storage_capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
    ]
