# Generated by Django 4.1.9 on 2023-08-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_rename_plant_constroller_type_plantcontroller_plant_controller_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plantcontroller',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plantcontrollertype',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
